### ISSUE TITLE
New 'Documentation' Folder Fails Travis Build Due to PB Sources Problems

### ISSUE THREAD

**Issue by tajmone** [fantaisie-software/purebasic#113]
I've noticed that `master` branch is no longer passing the Travis CI build, so I investigated the matter and found it's due to several problems with the newly added PB sources in the `Documentation/` directory:

1. __Spaces in filenames__ — The original `validate.sh` script didn't expect them, but I've not updated the script and will be creating a PR with the new version that can handle them — but first we need to rebase `devel` branch on `master`, because it's lagging too many commits behind (see #84).
2. __IDE Settings in sources__ — A couple of source files contained IDE settings, so the validation failed. I've also amended this and waiting to create a PR:
3. __Trailing Whitespaces__ — numerous files contain trailing whitespace which fails the validation build. But fixing them is problematic due to the last  problem in this list.
4. __Missing BOM__ — numerous sources lack a BOM; I've tried fixing them in bulk with a dedicated tool, but I get reports that many files are not in UTF-8!
3. __Wrong Encoding__ — it seems that many sources are not in UTF-8 — worst, some batch tools are seeing them as binary, so I'm not sure whether there might be some corrupted sources in the lot.

Before trying to fix the sources, so they meet the code styles enforced on the project, I wanted to make sure that some of them were not kept this way for special reasons — e.g. for building the documentation, which might expect the PB sources to be in some specific encoding for generating the CHM file, etc.

If that was the case, then we could simply exclude some folders from the test.

Otherwise, we'll have to investigate what's wrong. I've attempted to fix them many times over, with dedicated tools, and I keep getting warnings that some sources are in binary format, which means that some corrupt characters might have crept in during some past operations (either CMD, SVN or Git operations). These things do happen, especially with old code that has been dragged around, but it's better to fix these encoding issues as soon as possible.

E.g., in old projects I often encounter non-breaking spaces or a few other stray non visible characters which are left over from the DOS era, usually resulting from file redirection and piping gone wrong in the era of CodePages.

**Comment by fantaisie-software** [comment]
It's very possible than most of source are not in UTF-8. Is it only the .pb files ? There isn't a lot of them, so I can do it manually if needed.

**Comment by tajmone** [comment]
Yes, it's only the PB files.

> There isn't a lot of them, so I can do it manually if needed.

From the script log, I'd say there are a couple of hundred of them that need fixing, so I think that using dedicated tools (_iconv_, and other tools to add the BOM and remove trailing spaces without touching spaces-only lines) might be better, for opening them one by one in the IDE would be rather time consuming.

I didn't want to touch them because I though they might be injected into CHM docs, which can be fussy about encodings, and especially the BOM. But if you assure me it's OK to convert all of the PB sources in the `Documentation/` directory to UTF-8 with BOM, I can give it a ago, since I've already handled some fixes on some files.

But I still suspect the presence of some non visible chars (e.g. NBSP `0x0A0`) which is leading the tools to believe they are binary. This can be easily fixed via RegEx replace too.

**Comment by tajmone** [comment]
### Null Chars Found!

Ah, I knew it! 42 PB sources contained NULL chars, which caused tools (including Git) to see them as binary files.

I've removed all NULL chars and added a commit to PR #114 (still WIP).

Probably they sneaked in due to piping and redirection!

**Comment by tajmone** [comment]
OK, all issues have been fixed in PR #144, so I'll close this Issue.
