### ISSUE TITLE
Truncated Merge Messages?

### ISSUE THREAD

**Issue by tajmone** [fantaisie-software/purebasic#12]
Something is not quite right about the merge commits, the original commit message are getting truncated and all we are left with is a bare:

    Merge pull request #XX from xxxx/yyyy

and just the heading part of the original commit, which strips away all meaningful part of the commit description.

https://github.com/fantaisie-software/purebasic/commits/master

This could soon turn out into a nightmare! imagine having to sift through the whole repository history in a couple of years time, or using _blame_ and _history_ functionality to track specific changes; how are we going to make sense of what is what if messages are truncated?

Any idea why this is happening? Is it some mechanism in GitHub that truncates on empty lines?

It shouldn't happen, and it might be worthy amending the messages — even if it means force-pushing and rewriting the repo history on master branch! Usually this is a big "No! No!", for it could make participant who've been branching off their own work go bonkers ... but amending only the text is not that bad, for a simple rebase would fix everything since no contents changes are involved.

Recently I had to sift through the history of a repository dating back to the '90s, trying to find a lost document that was at some point removed from the repository and put on a (now dead) website. It was a long trip, and without blame, history and clean and meaningful commit message I wouldn't have managed to dig it out of that maze. So, yes a clean history matters indeed.

**Comment by fantaisie-software** [comment]
If you click on the #xx it show all the needed info, right ?

**Comment by tajmone** [comment]
I think I've understood the problem, it's because GitHub by default merges pull request, instead of just rebasing them. So you get both a commit with only the "merge xxxx" as well as the original commit. (I had forgotten this, since I always rebase or squash).

Usually when dealing with a single-commit PR rebasing can avoid that extra "merge xxxx" commit, and keep the history cleaner, whereas if you're merging a whole bunch of commits that make up a single feature or edit it makes sense to keep them "as a separate block" in the history (so to speak) by merging them and having a merge commit.

But this is the preferred way of doing it in GitHub, apparently.

https://stackoverflow.com/questions/8509396/git-pull-results-in-extraneous-merge-branch-messages-in-commit-log

Maybe the rationale is to preserve a clear timeline of who contributed what, but personally I think it clutters history (also, the meaningful info is always there, inside commits data).

When I look at the `git log` and see this:

```
commit b71a63ddc4bfeb07f0bf2d482597f31546904a7f
Merge: f6a982b aa2beb2
Author: fantaisie-software <58218392+fantaisie-software@users.noreply.github.com>
Date:   Mon Dec 9 10:01:46 2019 +0100

    Merge pull request #11 from tajmone/docs_work

    Silk Icons Preview

commit aa2beb2b4a1383bb771a1682e3bd218f4444eba5 (origin/docs_work, docs_work)
Author: tajmone <tajmone@libero.it>
Date:   Mon Dec 9 09:57:21 2019 +0100

    Silk Icons Preview

    In `PureBasicIDE/data/SilkTheme/`, create a markdown version of the
    `Readme.txt` file containing previews of all the icons.

    Original `Readme.txt` file preserved.

```

I personally find it redundant (and doubles the history-sifting work).

Many users choose to tweak the repository setting so that pull requests are rebased instead of merged, to avoid this type of redundancy. But the, it's a matter of choices I guess.

**Comment by fantaisie-software** [comment]
Isee what you mean. I think there is an option 'Rebase and merge' IIRC, will try this for next PR

**Comment by tajmone** [comment]
>  will try this for next PR

Please do, I think it's more important to keep a readable history than highlighting that some contributions are from external sources (after all, pull requests are not part of Git really, so this is only a problem when dealing with cross-repository contributions).

It's just that it looks confusing seeing two commits in a row where one seems like the resume of the other one (effectively, a spurious commit). Also, it doubles the repo history length with no real gains...

(again, sometime it makes sense to pack multiple commits into a merge that will show up nicely in the log, as an independent set of contributions in the graph)

**Comment by fantaisie-software** [comment]
Used 'Rebase and merge' and it worked as expected. Will do like that from now on

**Comment by tajmone** [comment]
@fantaisie-software, I've noticed (on my repo fork) that in the repository "__Setting__ » __Branches__" panel, when editing the __Branch protection rules__ option, there's a __Require linear history__ check-box:

> - [ ] __Require linear history__</br>Prevent merge commits from being pushed to matching branches.

I think that's the option to prevent the spurious commit messages discussed here, but I haven't managed yet to read the full documentation, so I'm not sure of all its implications. The [GitHub documentation] says (italics and bold added):

> ### Requiring a linear commit history
>
> You can require a linear commit history to block all merge commits from a protected branch. [...]
>
> Enforcing a linear commit history prevents merge commits from being pushed to the protected branch. This means that any pull requests merged into the protected branch *must use a __squash merge__ or a __rebase merge__*. A strictly linear commit history can help teams backtrack changes more efficiently.

This being a branch option, it can be set per branch (e.g. for `master` branch only) or using globbing patterns (e.g. `*` to apply the rule to all branches).

Maybe enabling this option for `master` branch would be a good idea, along with protecting the branch from force pushes.

## References

- [GitHub Help » Defining the mergeability of pull requests]
- [GitHub Help » Requiring a linear commit history]




[GitHub documentation]: https://help.github.com/en/github/administering-a-repository/requiring-a-linear-commit-history
[GitHub Help » Requiring a linear commit history]: https://help.github.com/en/github/administering-a-repository/requiring-a-linear-commit-history

[GitHub Help » Defining the mergeability of pull requests]: https://help.github.com/en/github/administering-a-repository/defining-the-mergeability-of-pull-requests
