### ISSUE TITLE
Problematic Repository Executable for Win Defender 

### ISSUE THREAD

**Issue by tajmone** [fantaisie-software/purebasic#124]
The repository is currently tracking an executable file which is causing some problems with Win 10's Defender:

- [`DialogManager/PureBasic.exe`][exe]

Win Defender keeps reporting it as a "severe threat" and quarantine it — which then show up in the working stage as a deleted file. Although it's a false positive, it's interfering with Git's file tracking.

I suggest that this binary is removed from the repository, unless it's essential for some reason.

[exe]: https://github.com/fantaisie-software/purebasic/blob/devel/DialogManager/PureBasic.exe "View file info in repository"

**Comment by fantaisie-software** [comment]
It's an error, it shouldn't be here

**Comment by tajmone** [comment]
OK. I've deleted it and create a PR (#126).

This exe was making my life hard, it kept being deleted and interfere with Git's work stage, and I had to restore it by discarding it via Git, but it was a back-and-forth situation, making interactive rebase operations hard. I know, I could have created an exception for the binary in Win Defender, but I'd rather not.

For some reasons, Win Defender lately has began to give a hard time for some PB compiled executables, especially if downloaded from the Internet. I'm not sure why these false positives are being triggered, but I've read on MS forums many complaints about the heuristics used by WD, especially from software companies which are experiencing issues with WD quarantining executables from their shipped products. Developers basically have to go through a process of reporting a false positive by submitting the fingerprint of their legitimate binaries, and then wait for MS to add it to the threats exclusion lists.

Most anti-viruses false positives are triggered by legitimate compression algorithms (e.g.  UPX) just because statistically they are often associated with malwares which rely on compression to obfuscate code. Anyways, these false-positives are becoming more of a problem and they're making many resources unusable.

I wonder what was triggering WD on this particular executable, and if anything could be done to prevent this from happening. I have the impression that the problem mostly affects old executables, and that by recompiling them with the latest PB version is often enough to placate Win Defender's paranoia of inexistent threats.

I've stopped trusting and using anti-viruses a number of years ago, when I realized that 90% of threats were due to UPX compression — by simply unpacking the executable, it would work fine without any threats reports. Ultimately, anti-viruses are the arch-enemies of software developers, but the problem remains on end-users' side, since most users do have an anti-virus on their OS, so there's always the worry that legitimate binaries might be arbitrarily swept aways at any time. 

I stick to Win 10's native Windows Defender, so at least I can have a reasonable expectation of how a vanilla Win 10 machine will behave, and I do get the occasional false positive interfering with my work.

Is there anything that can be done to mitigate these problems?

**Comment by fantaisie-software** [comment]
I don't think we can do anything except report it to Windows Defender as a wrong positive. Changing generated code each time we encounter this is not possible for us.

**Comment by tajmone** [comment]
> I don't think we can do anything except report it to Windows Defender as a wrong positive. Changing generated code each time we encounter this is not possible for us.

Thanks for the reply. I did some more searching on MS community forums, and discovered that (unfortunately) this is a widespread problem. Apparently, even certified software can trigger false positives (code signature is not enough as a guarantee, unless it's backed by a strong reputation). 

The worst part of this is that you can only submit binaries' fingerprints to Win Defender's white list if they were reported as threats — i.e. there's no mechanism for trusted vendors to submit their binaries to WD _before_ releasing them, in attempt to prevent WD from raising false positives and deleting core components of their apps of customers' computers. At least, not for small businesses (I'm sure for big players there are similar channels to prevent this from happening). For a small company, having to handle all the customers' support resulting from false positives, and having to repeatedly submit a white list request to MS can be quite a drain of resources.

This really sucks, because false positive reports can undermine customers' trust in the product, especially if they don't understand what false positives are and how anti-virus heuristics work. And even for those who do understand that the problem lies on the anti-virus side, having to work with a tool which is frequently sabotaged by WD can ultimately be a deterrent.

Anyhow, it's an old problem which is just getting worst, especially since code signing doesn't guarantee total immunity from false positives. So, I guess will have to live with it.
