### ISSUE TITLE
Enable Repository Discussions

### ISSUE THREAD

**Issue by tajmone** [fantaisie-software/purebasic#127]
@fantaisie-software,

Could you please enable __Discussions__ on the repository?

This is a recently added feature which allows to keep general discussions separate from Issues, thus allowing Issues to be used only for actual development and project editing tracking:

- [GitHub Help » Quickstart for GitHub Discussions]

> GitHub Discussions is a collaborative communication forum for the community around an open source project. Discussions are for conversations that need to be transparent and accessible but do not need to be tracked on a project board and are not related to code, unlike issues. Discussions enable fluid, open conversation in a public forum.
> 
> Discussions give a space for more collaborative conversations by connecting and giving a more centralized area to connect and find information.

[GitHub Help » Quickstart for GitHub Discussions]: https://docs.github.com/en/free-pro-team@latest/discussions/quickstart

**Comment by fantaisie-software** [comment]
Done !
