### ISSUE TITLE
Migrating PB/SB Help from DocMaker to Pandoc Markdown

### ISSUE THREAD

**Issue by tajmone** [fantaisie-software/purebasic#128]
@fantaisie-software,

I wanted to share a few thoughts on the PB/SB documentation.

Now that the PB Help sources are available under a FOSS license (something I've been longing for a long time) I've been considering working on a custom fork to enhance the quality of the HTML documents — syntax highlighting, a less eye-straining color scheme, added anchors for better cross-reference links, etc.

But, most of all, I was thinking of migrating the Help sources to a lightweight markup syntax, like [pandoc markdown] or [AsciiDoc], which would allow rich formatting and advanced features in a human-readable format, and benefit from well-established third party conversion tools like [pandoc] and [Asciidoctor].

## Migrating from DocMaker to Pandoc Markdown

Having now studied how the Help sources are organized with DocMaker Tags, I began realizing that the current documentation system could be easily ported to pandoc markdown with very little changes (most of them applicable by RegEx search-and-replace).

All of the current DocMaker Tags adopt a naming-convention (i.e. `@TagID()`) that allows them to be easily replaced by [PP] macros in pandoc markdown sources. [PP] is a generic pandoc preprocessor which provides many useful built-in macros allowing files inclusion, conditional preprocessor statements, file operations, and many other useful features, as well as defining custom macros that allow transforming source text before feeding it to pandoc — which includes the possibility of passing the captured text to an external script or binary tool, and then emit into the source document the output generated by that script/tool.

So, basically, the current PB Help sources could be ported to pandoc markdown by replicating the DocMaker Tags functionality as PP macros, which would allow to maintain the overall structure of the current documentation sources. Some DockMaker Tags would become obsolete, e.g. formatting tags for bold and other styles, and could be simply replaced by markdown formatting markup instead (e.g. `@Bold "bold` &rarr; `**bold**`, etc.); and HTML specific blocks might also be replaced with markdown formatting (e.g. tables, or separators like `<hr />` &rarr; `* * *`) which would work in all output formats.

You can check a small library of PP macros which I've created in the past, as an example of how macros can extend the basic pandoc functionality:

- https://github.com/tajmone/pandoc-goodies/tree/master/pp

## Advantages of Using Pandoc

The obvious advantages of moving from DocMaker to pandoc are:

- __Cross platform support__ — DocMaker is only available for Windows, pandoc is available for all PB-supported OSs.
- __Third-party tool maintenance__ — pandoc has a huge users base and the project is actively maintained by a large community of contributors, which ensures that the tool will be developing in the course of time, introducing new features, being updated to the latest standards of the various output formats, etc., removing from the PB/SB Help projects the burden of having to update DocMaker in time.
- __Richer formatting__ — [pandoc markdown] allow richer document formatting and features (e.g. footnotes) which are independent of the output format, and easy to work with when editing the documentation.
- __More output formats__ — pandoc supports all of DocMaker's target formats (HTML, website, LaTex, CHM) but also supports many other formats too. Creation of the PDF version wouldn't even require to go through LaTex, as pandoc can convert to ODT and allows document styles-templating via custom ODT document that will be used as templates, thus allowing fine-grain control over the final look and feel of the generated PDF.
- __Custom styling via templates__ — thanks to pandoc's template system, end users are free to customize the look and feel of the generated documents via custom templates.

Also, bear in mind that pandoc is a full-fledged document parser, which generated a document AST before converting it. Pandoc filters even allow manipulating the intermediate AST representation, to further customize the output; and pandoc accepts documents AST as an input format (either in JSON or in native Haskell representation), and also supports the AST as a valid conversion target (again, JSON or native Haskell).

Pandoc filters can be written in Lua or Haskell, natively, or in many other scripting languages, but also as binary applications; so it would be fairly easy to create custom filters in PureBasic, to manipulate the document AST via JSON, to obtain full control of the output document on a per-format basis.

## Final Thoughts

So, I'm definitely going to experiment porting the current PB Help to the above mentioned pandoc workflow, and see how it goes.

In the past, I had created a working prototype of a PureBasic pandoc CMS, called __Butler CMS__, for generating websites leveraging pandoc:

- https://github.com/tajmone/pb-archives-test/tree/source/_butler_

so I might reuse some of that code if it might help toward this goal. The tool basically allowed to organize loose documents into a book-like structured website, providing navigation menus and breadcrumbs, and other features to enhance the reading experience in HTML, as well as being most and foremost a pandoc-driver interface which allowed custom settings on a per-folder basis.

The main question is whether, in case of a successful port of the Help docs from DocMaker to pandoc, the new system might be adopted for the official PB/SB documentation, or if it should just become an independent fork, taking its own course and ultimately diverging from its upstream source.

Obviously, it would be preferable to have a single official source for the documentation, instead of diverging forks, but I do understand that in order to replace a well-tested documentation system and tool it would be necessary to ensure that the new system fully covers the previous needs, and possibly brings added benefits without introducing complexity.

My fear is that an independent fork of the documentation would soon die out, due to the efforts of trying to keep it en par with the upstream (which becomes rather difficult do deal with, once the sources are changed, no matter how slightly). Also, it would make much more sense to focus the community efforts in a single code base for the documentation, rather than spreading thin across multiple projects.

I personally think that moving to a standard tool like pandoc is a good choice, for it would not only improve the quality of the documentation, but also ensure that in the future the generated docs will always keep up with the evolving formatting standards. I'm also convinced that pandoc markdown is easier to work with in the source text, beside allowing more freedom of formatting.

So I'd like to hear your thoughts and advise on this, and whether you think it's a worthwhile effort.

[AsciiDoc]: https://asciidoc.org/ "Visit AsciiDoc (Python) website"
[Asciidoctor]: https://asciidoctor.org "Visit Asciidoctor website"

[pandoc]: https://pandoc.org "Visit pandoc website"
[pandoc markdown]: https://pandoc.org/MANUAL.html#pandocs-markdown "Learn more about pandoc's Markdown flavor"

[PP]: https://github.com/CDSoft/pp "Visit PP repository on GitHub"

**Comment by fantaisie-software** [comment]
Hi there ! I don't think it's necesseray, we like to have full control over doc format output and it actually works quite well. Also, pbdocmaker is ofcourse cross plateform and run on all supported OS (every OS build its own doc when creating the PB package).

**Comment by tajmone** [comment]
> I don't think it's necesseray, we like to have full control over doc format output and it actually works quite well. 

Ok, but I personally think that using pandoc with PP would have allowed greater control over the output, styles and allow end user customization of the base toolchain.

> Also, pbdocmaker is ofcourse cross plateform and run on all supported OS (every OS build its own doc when creating the PB package).

I didn't realize this (since its documentation only mentioned Windows I had inferred it was a Win-only tool).
