### ISSUE TITLE
Add Pre-Compiled C Components

### ISSUE THREAD

**Issue by tajmone** [fantaisie-software/purebasic#13]
From the various comments on the [open sourcing announcement on the Forum], it seems clear that for many PB users the C compilation side of this project is either a deterrent or an obstacle to participation in the project.

I was thinking that it might be a good idea to add to the repository the pre-compiled binaries of the C components required by the PB IDE, so that end users don't have to deal with all the trouble of setting up MSVC, etc. Providing binaries for all the supported OSs and architectures would be ideal.

Although tracking binary files with Git usually isn't a good idea, this context might be an exception for various reasons.

1. These binaries are not going to be huge in size, and unless they change very often they won't bloat up the index.
2. There are already some exe files tracked by the repo (`DialogManager/PureBasic.exe`, `PureBasicIDE/tools/png2ico.exe`).
3. Having access to correctly pre-compiled binaries makes testing more reliable because everyone uses the same exact components. If these binaries come from the maintainers everyone feels more confident about the general setup.
4. Contributors could focus just on PureBasic code in this project, without having to worry about C compilation in order to build the IDE.
5. It would definitely broaden the audience of PB users getting involved in building the IDE from sources (even the curious one might give it at try).

That is, unless the C compilation process is interdependent with the PB sources, requiring recompilation each time (haven't had a chance to look into it close enough).

Alternatively, these binaries could be hosted somewhere on the WWW (including the project's Wiki) and download links provided.

On Windows it might be quite troublesome to setup all the required MSVC tools, especially for those who have already installed a more recent Win SDK and VS product (if I remember correctly, you can't install multiple SKDs on the same machine).

For example, I recently had to install the MS Visual C++ 2019 Build Tools and the Win 10 SDK in order to work with [Rust] lang. I think that this precludes installing the Win 7 SDK on this machine, so I wouldn't be able to replicate the exact same conditions in which the IDE is being developed so far. I was hoping to be able to avoid having to tackle with (yet another) virtual machine and installing even more tools, if possible, for my machine is already bloated by all the dependencies of various languages and tools (Ruby for Windows now requires installing [MSYS2] too). So, unless it's _really_ necessary to do so, I'd like to skip the C part (and I'm not a fan of C either, if I have to be honest).

[open sourcing announcement on the Forum]: https://www.purebasic.fr/english/viewtopic.php?p=545582
[MSYS2]: https://www.msys2.org/
[Rust]: https://www.rust-lang.org/

**Comment by fantaisie-software** [comment]
That's a good idea, but it adds more burden on us, as we need to release new binaries for all 3 plateforms everytime a C code part is changed. I don't think I would start to do that, setupping the toolchain isn't that difficult IMHO

**Comment by tajmone** [comment]
> but it adds more burden on us, as we need to release new binaries for all 3 plateforms everytime a C code part is changed.

We could have Travis CI build and deploy on the repository the binaries for all three platforms. If all the tools involved in the C toolchain are freely downloadable and installable it shouldn't be a problem. 

But macOS and Linux are only available as 64-bit on Travis CI, and from what I've read lately both Ubuntu and macOS are dropping 32-bit support — macOS has already done that with Catalina; Ubuntu wanted to but stepped back after the outcry and Steam announcing that it would no longer support Ubuntu, but from what I gather it only postponed it for a grace-period. 

But yes, it seems that in the future these two OSs won't be supporting 32-bit any longer (say goodbye to Wine and other cool stuff), and compiling to 32-bit from an x64 machine might soon no longer work out of the box.

Probably the workaround would be using virtual machines, but it gets too complicated and lengthy.

I don't know the rationale behind that, since the x64 architecture is designed to run in 32 bit mode, and as far as I know Windows has no plans of dropping 32-bit support.

Anyhow, it should be possible via Travis CI, just as it's possible to publish static websites on GitHub Pages from sources.

Does the C code need to be changed often?

> I don't think I would start to do that, setupping the toolchain isn't that difficult IMHO

My worries are about the Win 7 SDK, for it might not be installable if you've already installed the Win 10 SDK. I'm not 100% sure, but I know that some editions conflict with others, but unfortunately the official documentation is spread thin and rather obscure on these issues.

**Comment by kenmo-pb** [comment]
It's not critical or urgent, but I too ask that we consider in the future: pre-compiled C components in the repo.

I've got the IDE repo building on two systems now (Win 7 + Win 10) and both times, getting Visual Studio and the Windows SDK working was the most time-consuming part and required much help. I started a thread of build tips on the forum, it should eventually be rewritten in Markdown here.

Mainly I had to uninstall newer VS and SDK versions, which didn't work "out of the box" with the PB repo. On Windows 7 I had to edit the registry (thanks ChrisR on the forum) to get the SDK 7.1 to install. I had to sign up for the (free) Visual Studio Dev Essentials program to get the VS 2013 download. Of course, this is all due to Microsoft, not the PB team. If I had to keep newer VS + SDK for other projects/work, I don't know if I'd have the PB repo working yet.

But anyway, I've got it running, and I look forward to submitting many features. Huge thanks for open-sourcing this! Great opportunity for learning and collaboration!

**Comment by tajmone** [comment]
Possibly you could add the pre-compiled binaries with every new IDE release — after all, you'll have to compiler them to create the distribution packages. I didn't mean to update the pre-compiled C bins every time the C source change, just with each PB release.

> Mainly I had to uninstall newer VS and SDK versions, which didn't work "out of the box" with the PB repo. 

That's my main issue, because I need the Win 10 SDK for Rust and Nim languages, so I'm not willing to drop it for an old and deprecated SDK.

> I had to sign up for the (free) Visual Studio Dev Essentials program to get the VS 2013 download.

Creating an account can be avoided if you download just the Visual C build tools, without the IDE — I didn't install the whole IDE, just the build tools and the SDK. From what I understand, you can install multiple MSVC build tools next to each other, because each one has its own batch files to setup the environment, but they all need the right SDK to be installed.

Also, since Microsoft acquired GitHub you can simply sign-in with your GitHub account.

Anyhow, installing MSVS products, especially older ones, is known to be problematic on newer versions of Windows. To install MSVS 2010 on Win 10 (another machine) it took me lot's of research to get it right, because unless you do the right steps in the right order you end up with a broken VS that can't update. And there's always the error with .NET 4.0, which hinders many installations (I saw it mentioned in the PB Forum, but the registry hack solution proposed is not the correct one, and it's risky).

Indeed, we should add troubleshooting tips on the Wiki.

**Comment by tajmone** [comment]
## Problems with Linux too

I've recently learned from a PM exchange on the PB Forum that some Linux users are experiencing problems building the C components too, due to conflicts with GTK2/3 which prevents them from compiling the C components.

The lack of official pre-compiled binaries is holding back potential contributors to the project — unless they are willing to "work in the dark" and commit untested changes, which we hope not.

## Sharing the Binaries on a Fork

I would like to ask users who managed to compiled the C components to share their binaries somehow (e.g. on a branch of their fork, inside their project Wiki, or on GDrive, etc.) so that all participants are able to test the IDE even if they can't install the MSVS dependencies on their machine, or have issue under their Linux version, or macOS, etc.

We'd need x32/x64 binaries for all three OSs.

This is not an ideal solution (unlike having the repository host the official binaries which will be used in the actual distribution package) but at least it would allow everyone to participate.

Anyone can help?

**Comment by tajmone** [comment]
## Does MSVS CE Support Compiler Optimization?

@fantaisie-software, do you know if the Community Edition of MSVS 2013 supports compiler optimization or not?

I wasn't able to find a confirmation to this and MS documentation is a bit obscure on the topic. For example, I've learned that the Community Edition of MSVS 2010 _does not_ support compiler optimization (or at least, it didn't support it initially, but I'm not sure if the latest updates add optimization support or not). Yet, many people believe that MSVS 2010 CE is just like the full edition, and it really took me some digging to get confirmation that it doesn't support compiler optimizations.

I'm not sure what the current MS policies are for the CE of VS products in this respect. I know that the CE editions do lack support for some features, but these are mostly IDE related, so it might just be that for the sake of promoting VS they now include compiler optimization in the free edition too. It's just that I couldn't get confirmation of that.

## Is VS 2010 Still Required for PB Libs?

Also, I'd like to ask @fantaisie-software if Pure libraries for Windows still need to be compiled using VS 2010 and the Win 7 SDK?

That is what I've found in the PB Forums, and the PB SDK documentation also recommends using VS 2010 to build libraries as it's the version used by the PureBasic Team to build the PB package.

Is this still the case? or can we compile PB libs using more recent versions of VS?

**Comment by kenmo-pb** [comment]
I can add Windows binaries to a fork. I just need to figure out exactly which files are necessary, since I think many intermediate files are also created.

**Comment by kenmo-pb** [comment]
@tajmone I added the Windows **x86** C binaries to my branch `add-c-binaries`
https://github.com/kenmo-pb/purebasic/tree/add-c-binaries

I tried to do the same with **x64** but I am getting another (new for me) `make` error, posted to the forum:
https://www.purebasic.fr/english/viewtopic.php?f=18&t=74184&p=547505#p547505
