### ISSUE TITLE
PureBasic Help: Enforce Consistent Encoding in '.txt' Sources 

### ISSUE THREAD

**Issue by tajmone** [fantaisie-software/purebasic#135]
@Naheulf discovered that some of **PB Help**'s [`Documentation/`][Documentation] sources are encoded in ISO-8859-1, whereas most sources are in UTF-8 (see #120).

We should enforce consistent encoding in all documentation sources:

- [ ] Detect sources that are not in UTF-8 encoding and convert them from their original encoding to UTF-8:
    + [ ] [`Documentation/English/`][Documentation/English]
    + [ ] [`Documentation/French/`][Documentation/French]
    + [ ] [`Documentation/German/`][Documentation/German]

Preferably, a native speaker of the language should carry out the encoding fixes for that language version, so that he/she'll be able to inspect the affected files and check that special characters are correctly preserved (e.g. accented letters, diacritics, etc., which are frequent in German and French).

-------------------------------------------------------------------------------

@fantaisie-software, can you confirm that the documentation sources' default encoding should be UTF-8?

Or was the DocMaker created at the time PB was ASCII only, and thus expects ISO-encoded sources? Since special chars that differ between UTF-8 and ISO-8859-1 don't occur frequently, they could easily slip through corrupted and go unnoticed.

[Documentation]: https://github.com/fantaisie-software/purebasic/tree/devel/Documentation "View repo folder"

[Documentation/English]: https://github.com/fantaisie-software/purebasic/tree/devel/Documentation/English
[Documentation/French]: https://github.com/fantaisie-software/purebasic/tree/devel/Documentation/French
[Documentation/German]: https://github.com/fantaisie-software/purebasic/tree/devel/Documentation/German

**Comment by tajmone** [comment]
# UTF-8 Validation Tests

I've written a script to quickly check if the various `.txt` sources are valid UTF-8, and as it turns out, many aren't.

The test was done by attempting to convert from UTF-8 via `iconv` (see [StackOverflow](https://stackoverflow.com/questions/115210/how-to-check-whether-a-file-is-valid-utf-8/115262#115262)):

```
$ iconv -f UTF-8 your_file > /dev/null; echo $?
```

Below are the list of non-UTF-8 files, grouped by language folder. As the results show, in the `English/` subfolder most sources are valid UTF-8 (which would make sense anyway, since it's the language with less special letters in alphabet), whereas `French/` and `German/` have a high number of non-UTF-8 files.

| Help Folder   | non-UTF8 files   |
| :------------ | ---------------: |
| `English/`    | 24               |
| `French/`     | 168              |
| `German/`     | 187              |

## ISO-8859-1?

Since there roughly 196 `.txt` files in each locale directory, I'm starting to think that these sources are using an encoding like ISO-8859-1.

If this was the case, it might be a problem, since most modern editors will treat them as UTF-8 by default, and will most likely break the original ISO encoding with paste operations (i.e. switching to UTF-8 if the clipboard contains UTF-8 encoded text).

In my experience, based on working with legacy tools that don't support Unicode sources, working with ISO files today (without experiencing problems) is quite hard, even if adopting a custom extension to force the editor to associate it with the ISO encoding (let alone using a generic extension like `.txt`).

If DocMaker isn't currently loading the PB Help sources as UTF-8 encoded, it should be changed to do so.

Also, it would be a good idea to adopt a dedicated file extension, instead of just `.txt` (e.g. `.pbhelp`, `.pb-help`, or something like it).

### English

Only 24 files didn't pass UTF-8 validation:

<details><summary>CLICK TO EXPAND</summary>

- `Cipher.txt`
- `MainGuide/contact.txt`
- `MainGuide/history.txt`
- `MainGuide/order.txt`
- `MainGuide/regform2.txt`
- `Preference.txt`
- `Reference/asciitxt`
- `Reference/general_rules.txt`
- `Reference/ide_debugtools.txt`
- `Reference/ide_externaltools.txt`
- `Reference/ide_preferences.txt`
- `Reference/ide_tools.txt`
- `Reference/license_engine3d.txt`
- `Reference/purebasic_objects.txt`
- `Reference/ug_constants.txt`
- `Reference/ug_directives.txt`
- `Reference/ug_gui.txt`
- `Reference/ug_loops.txt`
- `Reference/ug_pb_any1.txt`
- `Reference/ug_pb_any2.txt`
- `Reference/ug_variables.txt`
- `Reference/variables.txt`
- `String.txt`
- `Window.txt`

</details>

### French

168 files didn't pass UTF-8 validation:

<details><summary>CLICK TO EXPAND</summary>


- `2DDrawing.txt`
- `Array.txt`
- `AudioCD.txt`
- `Billboard.txt`
- `Camera.txt`
- `CGI.txt`
- `Cipher.txt`
- `Clipboard.txt`
- `Console.txt`
- `Database.txt`
- `Date.txt`
- `Debugger.txt`
- `Desktop.txt`
- `Dialog.txt`
- `DragDrop.txt`
- `Engine3D.txt`
- `Entity.txt`
- `EntityAnimation.txt`
- `File.txt`
- `FileSystem.txt`
- `Font.txt`
- `Ftp.txt`
- `Gadget.txt`
- `Gadget3D.txt`
- `Help.txt`
- `Http.txt`
- `Image.txt`
- `ImagePlugin.txt`
- `Joint.txt`
- `Joystick.txt`
- `Json.txt`
- `Keyboard.txt`
- `Library.txt`
- `Light.txt`
- `List.txt`
- `Mail.txt`
- `MainGuide/avertis.txt`
- `MainGuide/changes.txt`
- `MainGuide/contact.txt`
- `MainGuide/greats.txt`
- `MainGuide/history.txt`
- `MainGuide/install.txt`
- `MainGuide/intro.txt`
- `MainGuide/ogre_mit.txt`
- `MainGuide/order.txt`
- `MainGuide/system.txt`
- `Map.txt`
- `Material.txt`
- `Math.txt`
- `Memory.txt`
- `Menu.txt`
- `Mesh.txt`
- `Mouse.txt`
- `Movie.txt`
- `Music.txt`
- `Network.txt`
- `Node.txt`
- `NodeAnimation.txt`
- `OnError.txt`
- `Packer.txt`
- `Particle.txt`
- `Preference.txt`
- `Printer.txt`
- `Process.txt`
- `Reference/ascii.txt`
- `Reference/binary.txt`
- `Reference/break_continue.txt`
- `Reference/cli_compiler.txt`
- `Reference/colortable.txt`
- `Reference/compilerdirectives.txt`
- `Reference/compilerfunctions.txt`
- `Reference/data.txt`
- `Reference/debugger.txt`
- `Reference/define.txt`
- `Reference/dim.txt`
- `Reference/dll.txt`
- `Reference/enumerations.txt`
- `Reference/foreach_next.txt`
- `Reference/formulas.txt`
- `Reference/for_next.txt`
- `Reference/general_rules.txt`
- `Reference/global.txt`
- `Reference/gosub_return.txt`
- `Reference/handles.txt`
- `Reference/ide_commandline.txt`
- `Reference/ide_compiler.txt`
- `Reference/ide_debugger.txt`
- `Reference/ide_debugtools.txt`
- `Reference/ide_editing.txt`
- `Reference/ide_externaltools.txt`
- `Reference/ide_files.txt`
- `Reference/ide_form.txt`
- `Reference/ide_help.txt`
- `Reference/ide_preferences.txt`
- `Reference/ide_projects.txt`
- `Reference/ide_start.txt`
- `Reference/ide_tools.txt`
- `Reference/if_endif.txt`
- `Reference/import_endimport.txt`
- `Reference/includes.txt`
- `Reference/inlinedasm.txt`
- `Reference/interfaces.txt`
- `Reference/license_engine3d.txt`
- `Reference/links.txt`
- `Reference/macros.txt`
- `Reference/memory.txt`
- `Reference/migration.txt`
- `Reference/migration_520_540.txt`
- `Reference/migration_530_540.txt`
- `Reference/migration_540_550.txt`
- `Reference/migration_550_560.txt`
- `Reference/migration_560_572.txt`
- `Reference/module.txt`
- `Reference/newlist.txt`
- `Reference/newmap.txt`
- `Reference/number_tab.txt`
- `Reference/others.txt`
- `Reference/portnumbers.txt`
- `Reference/procedures.txt`
- `Reference/protected.txt`
- `Reference/prototypes.txt`
- `Reference/pseudotypes.txt`
- `Reference/purebasic_objects.txt`
- `Reference/repeat_until.txt`
- `Reference/residents.txt`
- `Reference/runtime.txt`
- `Reference/select_endselect.txt`
- `Reference/several_pb.txt`
- `Reference/shared.txt`
- `Reference/static.txt`
- `Reference/structures.txt`
- `Reference/subsystems.txt`
- `Reference/threaded.txt`
- `Reference/unicode.txt`
- `Reference/variables.txt`
- `Reference/vectorcheminsegments_fr.txt`
- `Reference/while_wend.txt`
- `Reference/winmessages.txt`
- `Reference/with_endwith.txt`
- `RegularExpression.txt`
- `Requester.txt`
- `Runtime.txt`
- `Scintilla.txt`
- `Screen.txt`
- `SerialPort.txt`
- `Sort.txt`
- `Sound.txt`
- `Sound3D.txt`
- `SoundPlugin.txt`
- `SpecialEffect.txt`
- `Spline.txt`
- `Sprite.txt`
- `StaticGeometry.txt`
- `StatusBar.txt`
- `String.txt`
- `System.txt`
- `SysTray.txt`
- `Terrain.txt`
- `Text3D.txt`
- `Texture.txt`
- `Thread.txt`
- `Toolbar.txt`
- `VectorDrawing.txt`
- `Vehicle.txt`
- `VertexAnimation.txt`
- `Window.txt`
- `Window3D.txt`
- `Xml.txt`

</details>

### German

187 files didn't pass UTF-8 validation:

<details><summary>CLICK TO EXPAND</summary>

- `2DDrawing.txt`
- `Array.txt`
- `AudioCD.txt`
- `Billboard.txt`
- `Camera.txt`
- `CGI.txt`
- `Cipher.txt`
- `Clipboard.txt`
- `Console.txt`
- `Database.txt`
- `Date.txt`
- `Debugger.txt`
- `Desktop.txt`
- `Dialog.txt`
- `DragDrop.txt`
- `Engine3D.txt`
- `Entity.txt`
- `EntityAnimation.txt`
- `File.txt`
- `FileSystem.txt`
- `Font.txt`
- `Ftp.txt`
- `Gadget.txt`
- `Gadget3D.txt`
- `Help.txt`
- `Http.txt`
- `Image.txt`
- `ImagePlugin.txt`
- `Joint.txt`
- `Joystick.txt`
- `Json.txt`
- `Keyboard.txt`
- `Library.txt`
- `Light.txt`
- `List.txt`
- `Mail.txt`
- `MainGuide/avertis.txt`
- `MainGuide/changes.txt`
- `MainGuide/contact.txt`
- `MainGuide/greats.txt`
- `MainGuide/history.txt`
- `MainGuide/install.txt`
- `MainGuide/intro.txt`
- `MainGuide/order.txt`
- `MainGuide/pcre.txt`
- `MainGuide/regform2.txt`
- `MainGuide/system.txt`
- `Map.txt`
- `Material.txt`
- `Math.txt`
- `Memory.txt`
- `Menu.txt`
- `Mesh.txt`
- `Mouse.txt`
- `Movie.txt`
- `Music.txt`
- `Network.txt`
- `Node.txt`
- `NodeAnimation.txt`
- `OnError.txt`
- `Packer.txt`
- `Particle.txt`
- `Preference.txt`
- `Printer.txt`
- `Process.txt`
- `Reference/ascii.txt`
- `Reference/binary.txt`
- `Reference/break_continue.txt`
- `Reference/cli_compiler.txt`
- `Reference/colortable.txt`
- `Reference/compilerdirectives.txt`
- `Reference/compilerfunctions.txt`
- `Reference/data.txt`
- `Reference/debugger.txt`
- `Reference/define.txt`
- `Reference/dim.txt`
- `Reference/dll.txt`
- `Reference/enumerations.txt`
- `Reference/foreach_next.txt`
- `Reference/formulas.txt`
- `Reference/for_next.txt`
- `Reference/general_rules.txt`
- `Reference/global.txt`
- `Reference/gosub_return.txt`
- `Reference/handles.txt`
- `Reference/ide_commandline.txt`
- `Reference/ide_compiler.txt`
- `Reference/ide_debugger.txt`
- `Reference/ide_debugtools.txt`
- `Reference/ide_editing.txt`
- `Reference/ide_externaltools.txt`
- `Reference/ide_files.txt`
- `Reference/ide_form.txt`
- `Reference/ide_help.txt`
- `Reference/ide_preferences.txt`
- `Reference/ide_projects.txt`
- `Reference/ide_start.txt`
- `Reference/ide_tools.txt`
- `Reference/if_endif.txt`
- `Reference/import_endimport.txt`
- `Reference/includes.txt`
- `Reference/inlinedasm.txt`
- `Reference/interfaces.txt`
- `Reference/license_application.txt`
- `Reference/license_engine3d.txt`
- `Reference/links.txt`
- `Reference/macros.txt`
- `Reference/memory.txt`
- `Reference/migration.txt`
- `Reference/migration_520_540.txt`
- `Reference/migration_530_540.txt`
- `Reference/module.txt`
- `Reference/newlist.txt`
- `Reference/newmap.txt`
- `Reference/number_tab.txt`
- `Reference/others.txt`
- `Reference/portnumbers.txt`
- `Reference/procedures.txt`
- `Reference/protected.txt`
- `Reference/prototypes.txt`
- `Reference/pseudotypes.txt`
- `Reference/purebasic_objects.txt`
- `Reference/repeat_until.txt`
- `Reference/residents.txt`
- `Reference/runtime.txt`
- `Reference/select_endselect.txt`
- `Reference/several_pb.txt`
- `Reference/shared.txt`
- `Reference/static.txt`
- `Reference/structures.txt`
- `Reference/subsystems.txt`
- `Reference/threaded.txt`
- `Reference/ug_advanced.txt`
- `Reference/ug_constants.txt`
- `Reference/ug_data.txt`
- `Reference/ug_decisions.txt`
- `Reference/ug_directives.txt`
- `Reference/ug_files.txt`
- `Reference/ug_firststeps.txt`
- `Reference/ug_graphics.txt`
- `Reference/ug_gui.txt`
- `Reference/ug_inputoutput.txt`
- `Reference/ug_keywords.txt`
- `Reference/ug_libraryfunctions.txt`
- `Reference/ug_loops.txt`
- `Reference/ug_memory.txt`
- `Reference/ug_overview.txt`
- `Reference/ug_pb_any1.txt`
- `Reference/ug_pb_any2.txt`
- `Reference/ug_procedures.txt`
- `Reference/ug_string.txt`
- `Reference/ug_textoutput.txt`
- `Reference/ug_tips.txt`
- `Reference/ug_variables.txt`
- `Reference/unicode.txt`
- `Reference/variables.txt`
- `Reference/while_wend.txt`
- `Reference/winmessages.txt`
- `Reference/with_endwith.txt`
- `RegularExpression.txt`
- `Requester.txt`
- `Runtime.txt`
- `Scintilla.txt`
- `Screen.txt`
- `SerialPort.txt`
- `Sort.txt`
- `Sound.txt`
- `Sound3D.txt`
- `SoundPlugin.txt`
- `SpecialEffect.txt`
- `Spline.txt`
- `Sprite.txt`
- `StaticGeometry.txt`
- `StatusBar.txt`
- `String.txt`
- `System.txt`
- `SysTray.txt`
- `Terrain.txt`
- `Text3D.txt`
- `Texture.txt`
- `Thread.txt`
- `Toolbar.txt`
- `VectorDrawing.txt`
- `VertexAnimation.txt`
- `Window.txt`
- `Window3D.txt`
- `Xml.txt`

</details>

**Comment by Naheulf** [comment]
Should we also use utf-8 **with BOM** like all `*.pb` files ? And can it be a good idea to force the `BOM` usage for all utf8 files in the repo (except the high sensitive makefile) ?

**Comment by tajmone** [comment]
> Should we also use utf-8 with BOM like all *.pb files ? And can it be a good idea to force the BOM usage for all utf8 files in the repo (except the high sensitive makefile) ?

It might make sense since these are PB related files, but this would require DocMaker to be updated accordingly (i.e. enforce UTF-8 if it's using ISO encoding, and the BOM). But this would only make sense if adopting a custom file extension for the Help sources, for most editors wouldn't add a BOM by default.

Technically speaking, using a BOM in UTF-8 files is generally discouraged (although it's recognized as a valid practice), and it's mostly found with Microsoft applications, and almost never encountered in the Unix world. But since PB sources uses the BOM, it might be a viable solution, and it might also preserve backward compatibility (in case DocMaker is using ISO encoded files right now, for it could fallback to ISO-8859-1 if no BOM is encountered).

**Comment by Naheulf** [comment]
I just tested it and... it does NOT works:
![image](https://user-images.githubusercontent.com/14990967/109950357-b5d1b180-7cdc-11eb-9a8a-c99517b5af67.png)

**Comment by tajmone** [comment]
> I just tested it and... it does NOT works:

That's really bad news, and I'm speaking from practical experience.

In the past three years I've been managing a number of repositories for a legacy text adventures language which uses ISO-8859-1 for its source files, commands scripts and logs, and I've faced many problems related to encoding.

I had to create my own editor syntax for Sublime Text in order to enforce ISO-8859-1 for those files, specifying it as both their _default_ and _fallback_ encoding, but even with that ...

- Paste operations tend to break the encoding because there's no mechanism in place to convert on the fly clipboard contents, so pasting any one-byte character that is differently encoded in UTF-8 will cause the source file to switch to UTF-8 (but at least the editor warns you, because of the fallback encoding setting being bypassed).
- Also, Windows Alt-Codes to insert special characters tend to break a document; again, due to the editor's lack of context awareness when it comes to encoding during text insertion operations.

For those ISO files that had an extension of their own, things weren't so bad (with the proper editor settings associated to them), but I had to adopt my own custom extensions for the original `.log` files, because otherwise the editor will consider them as UTF-8 (and I can't enforce another encoding in such a widely used file extension).

Even with all that in place, I'm often faced with encoding corruption issues when third parties contribute to the projects via Git.

Git doesn't offer any feature when it comes to enforcing encoding, and it often does a bad job at handling ISO files in diffs and changes.

EditorConfig settings are supposed to support ISO encodings, but how this works out in practice it's really up to how specific editors and IDEs support EditorConfig (natively or via third party packages/plug-ins).

The Eclint validation tool (which we use here to validate commits and PRs) does a very poor job at validating ISO-8859-1/Latin-1 files (and since it's a dead tool it won't be updated).

# DocMaker Proposed Solutions

Here we have the same problem, because of the `.txt` extension. So I think it's really important to adopt a custom dedicated extension, and possibly switch to UTF-8 — although just adopting a custom extension _might_ mitigate the problem, assuming end users can associate it with the ISO encoding and that their editor does a decent job at enforcing it.

But anyways, either of these solutions would require updating DocMaker, and breaking backward compatibility. But as it was mentioned earlier, the BOM could be used to distinguish the new UTF-8 sources from the older ISO sources, which would preserve backward compatibility as far as encoding goes; but handling different file extensions might require some additional CLI/GUI options to allow DocMaker to also work with old sources.

Considering that right now we the documentation doesn't even mention the required encoding for the Help sources, and that XSL entities are not being supported (as you mentioned), the situation is rather grim, and chances are that these sources will get encoding corrupted.

Ultimately, it boils down on whether Fred wants to update DocMaker, and if he deems that this problem warrants introducing backward-compatibility breaking problems.

# Immediate Repository Suggested Actions

What we surely need to do right now is:

- [ ] Update the docs mentioning that:
    + [ ] Help sources must be ISO-8859-1 encoded.
    + [ ] XSL entities are not supported.
- [ ] Tweak `validate.sh` and add ISO-8859-1 validation (via `iconv`?) for all Help sources.

**Comment by Naheulf** [comment]
One "good" news : HTML entities works inside a `@FormatIf HTML` section.
For example : 
```
@Title Break : Continue

@FormatIf HTML
  <p>&nbsp;</p>
  <center> 
  <table WIDTH="96%"  border="1" cellspacing="0" bordercolordark="white" bordercolorlight="black">
  <caption> <b>Résumé des fonctions:</b> </caption>
  <tr>
    <td align="center" vAlign="center" nowrap><a href="#Break"><u>&#128512;Break&Eacute; &#</u></a></td>
    <td align="center" vAlign="center" nowrap><a href="#Continue"><u>Continue</u></a></td>
  </tr>
    </table>
  </center>
  <p>&nbsp;</p>
@FormatEndIf
<u>&#128512;Break&Eacute; &#</u>
```
give:
![image](https://user-images.githubusercontent.com/14990967/110073792-4f05d400-7d80-11eb-9efc-2c58ac72ec60.png)
without editing the intermediate html file.

**Comment by tajmone** [comment]
> One "good" news : HTML entities works inside a `@FormatIf HTML` section.

Hopefully, future versions of DocMaker could take advantage of the [`UnescapeString(String$, #PB_String_EscapeXML)`][UnescapeString()] command and escape XSL entities (which PB calls "XML entities") anywhere.



[UnescapeString()]: https://www.purebasic.com/documentation/string/unescapestring.html

**Comment by Naheulf** [comment]
We also have the de-facto answer for #137 (at least for French)

**Comment by tajmone** [comment]
I'm converting this Issue into a Discussion since it's becoming more a discussion thread on the current encoding problems of the repository and the possible solutions, rather than a clean-cut Issue for immediate repository actions.

Once Fred and @t-harter will have joined the discussion, and we come up with some agreed upon decisions, we can then create a dedicated Issue will the task list of actions to solve the encoding problem.
