### ISSUE TITLE
Stripping the Downloadable Zip down to the Essentials

### ISSUE THREAD

**Issue by tajmone** [fantaisie-software/purebasic#14]
This project is most likely going to have two types of users:

1. Those who will clone/fork and edit the repository via Git (aka the "Gitters").
2. Those who'll just go for the __Download Zip__ option from the <kbd>Clone or download</kbd> drop-down menu in the main page.

For the latter, it might make sense to add some [`export-ignore`][export-ignore] attributes in `.gitattributes` to exclude some strictly Git-related contents from the downloaded archive (`.gitignore`, `.gitattributes`, etc.) so they get a trimmed down version designed for those who aren't interested in the version control aspects of the project.

This is probably exactly what this type of users would be looking for, i.e. to get a slimmer version so they can focus only on the actual project contents. In this context, _less is more_, and Git settings and continuous integration files become just distracting "clutter".

`export-ignore` rules grant us fine-grain control over what should be left out from the downloadable Zip archive.

Right now, I can think only of the various settings files for Git, EditorConfig and Travis CI (and related CI scripts), but probably there are also other files that might qualify for exclusion.

Probably the whole `.git/` folder (hidden, but always there) should be excluded if we decide to make the Zip archive a "Git detached" version of the project; this would reduce the archive size significantly since it contains all the snapshots of the repository history.

Since the README doesn't yet provide instruction on how to get hold of a copy of the project, it might be the right time to add those instructions as well as to clarify the difference between _cloning_, _forking_ and _downloading an archive_ of the project. For GitHub newbies none of this might be obvious, and only the last two options are available to those who don't own a GitHub account.

Based on my experience on the PureBasic Forums, I think that users of the second type are going to be numerous (and might actually outnumber the "Gitters"). But they will probably be interested in getting a copy of this repository for local use, so we should keep it into account.

# References

- [Git Reference Manual » git archive]
- [Git Reference Manual » gitattributes » Creating an archive]
- [Git Book » §8.2 Git Attributes » Exporting Your Repository]
- _[Using git attributes to exclude files from your release]_ — by Sean Hamlin.

[export-ignore]: https://git-scm.com/docs/gitattributes#_code_export_ignore_code "Read Git docs on the 'export-ignore' attributes"

[Git Reference Manual » git archive]: https://git-scm.com/docs/git-archive
[Git Reference Manual » gitattributes » Creating an archive]: https://git-scm.com/docs/gitattributes#_creating_an_archive

[Git Book » §8.2 Git Attributes » Exporting Your Repository]: https://git-scm.com/book/en/v2/Customizing-Git-Git-Attributes#_exporting_your_repository

[Using git attributes to exclude files from your release]: https://www.pixelite.co.nz/article/using-git-attributes-exclude-files-your-release/

**Comment by fantaisie-software** [comment]
Makes sense
