### ISSUE TITLE
Safeguards Against PureBasic IDE Settings

### ISSUE THREAD

**Issue by tajmone** [fantaisie-software/purebasic#15]
We need to address some potential interferences with Git by the PureBasic IDE changing source files at save time, which could lead to false-positive modified files in Git working directory.

The main sources of this problem are:

1. A contributor's IDE being configured to "__Save Setting to__ » __The end of the Source file__".
2. The presence in the repository of PB project files (`.pbp`) being tracked.

# Save Setting to

The first problem would cause PB sources to be constantly modified by each end-user that opens the file in the PB IDE, for the IDE would store user-associated info (like PBCompiler version, cursor position, etc.) at the end of the source file, causing Git to detect it as modified even though the user didn't actually edit its contents (I refer to this as a _false positive_ change).

These false positives can easily end up being committed to the project, especially when the user has edited many files, for he/she might just add all changed files to the stage and commit without noticing it. These changed settings would then be picked up by other users' IDE after pulling the repository updates, if they happen to adopt the same IDE "__Save Setting to__" configuration. Because the IDE hides these end-of-file settings from the user, it's easy to forget about them or fail to notice their presence (unless one looks closely at the commit diff).

In this case, the solution is rather straightforward, for we only need to warn users (in `Contributing.md`) about the need to choose another option for "__Save Setting to__" — ideally, "__A common file project.cfg for every directory__" would be the best choice in collaborative projects, but "__The file &lt;filename&gt;.pb.cfg__" is also fine (and, of course, there's always "__Don't save anything__", but this might be too drastic and unnecessary).

## Git-ignoring .cfg Files

In any case, opting for the other two alternatives would still generate inside the repository tree one or more ever-changing files that Git would detect as being modified. For this reason, we ought to ad to `.gitignore` exclusion rules for these files:

```gitignore
project.cfg
*.pb.cfg
*.pbi.cfg
```

Currently, there are a various `project.cfg` in the repository:

    project.cfg
    DialogManager/project.cfg
    DialogManager/project.cfg
    PureBasicIDE/project.cfg
    PureBasicIDE/data/project.cfg
    PureBasicIDE/FormDesigner/project.cfg
    PureBasicIDE/sdk/project.cfg
    PureBasicIDE/tools/project.cfg

> __NOTE__ — the proposed exclusion rules are already in place in the[ `.gitignore` file](https://github.com/fantaisie-software/purebasic/blob/master/.gitignore#L6):
>
> ```gitignore
> ## ===============
> ## PureBasic files
> ## ===============
> ## Exclude PB project and configuration files from repository to avoid
> ## personal data leaks and interferences with Git working directory, since
> ## these files differ on each end-user machine and change at every project
> ## save, polluting the working directory.
> *.pb.cfg
> *.pbi.cfg
> *.pbp
> project.cfg
> ```
>
> but since these rules were added _after_ those `project.cfg` were already being tracked, they are not affecting them. At some point, we should remove those files from the index so they get ignored by Git.

Therefore, the `.gitignore` approach would effectively protect the project from ever-changing files from both the "__common file project.cfg__" and "&lt;__filename&gt;.pb.cfg__" configurations.

## Validating PB Sources

The `.gitignore` approach does not shield the project from the "__Save Setting to__ » __The end of the Source file__" though. In this case, we need to trust end users to follow the _Contributors' Guidelines_. But, to be on the safe side, we could enforce a validation of the PB sources.

In the past year, @SicroAtGit and I have been exploring the idea of creating a PureBasic tool to manage third party assets, a sort of package manager that would extract assets info from header comments, as well as generate documentation from comments (via AsciiDoc) and carry out some basic integrity checks.

@SicroAtGit has written an efficient PB sources validator that detects and strips away IDE configurations at the end of source files. You can find a prototype of this tool (MIT licensed) at:

- https://github.com/tajmone/PBCodeArcProto/blob/master/_tempwork/CodesCleaner.pb#L93

A similar tool could be added to the repository to enable users to validate their code before submitting it (along with the current `./validate.sh` script that checks EditorConfig compliance).

If we were to also include in the repository a precompiled binary (possibly, Linux x64) of this CLI tool, we could then add it to the Travis CI build to capture these problems when commits and PRs come in, so they don't get merged into the codebase.

Furthermore, we could configure the repository to use it as a Git filter to validate commits. Although this might add some overhead to commit operations, it would prevent accidentally committing IDE setting at the end of the sources (either by generating an error and aborting the commit, or by simply stripping away the IDE settings lines from the file that gets actually indexed).

# Project Files

PB project files are rather problematic for they also leak some information on the user machine (paths with sensitive data, etc.), ad they are also subject to changes at save-time.

The easiest solution I've come up with for this problem is to Git-ignore all `*.pbp` files except for some "project template", which are not intended to be opened directly in the IDE, but copied with a new name before use.

E.g., add to the repository a `MyProject.sample.pbp` project file, which is stripped of all user-specific data (absolute paths, history, etc.). End users would then copy and rename the file to `MyProject.pbp` (which is then ignored by Git) and use this file with the IDE.

Although it's far from a perfect solution, at least it allows to provide the core data of a project that is usable (the IDE simply rebuilds the stripped out entries) without affecting Git working directory.

This solution only requires two line inside `.gitignore`, an exclusion rule and and an exception rule:

```gitignore
*.pbp
!*.sample.pbp
```

Other possible solutions that came to my mind focused on creating a tool to strip away from `*.pbp` files all user-specific data. The problem is that for this to work users would have to close the PB IDE, run the tool and then commit, because the IDE updates the project files both at save and exit time.

Again, a Git filter could also be configured, so that user-specific entries are filtered at indexing time, but a full XML parser would definitely introduce overhead to the commit stage.

-------------------------------------------------------------------------------

I had considered using the `git --assume-unchanged` option to circumvent the false positive changes mentioned here, but it seems a weak solution for it was intended as a temporary measure to be used locally, and not project-wide.

The above proposed solutions are the best I could come up with in order to prevent headaches with IDE settings creeping into codebase and causing a snow-ball effect of ever-changing PB sources were each user's IDE tries to take over the tracked `.cfg` settings files or (worst) the end portion of source files.

**Comment by fantaisie-software** [comment]
I agree with all this, feel free to submit a PR (removing the .cfg, changing the .pbp into a template). About the save at the end of source, I think the new PB install default is now the project.cfg, so it shouldn't be a big problem. I will check the PR to ensures there is no specific source data in it.

**Comment by tajmone** [comment]
@fantaisie-software,

> I agree with all this, feel free to submit a PR [...] I will check the PR to ensures there is no specific source data in it.

I've been looking into how to circumvent `*.pbp` project files from exposing personal data and being overriden by end user. The `*.sample.pbb` approach is a viable solution but ... my main concern is about what happens when the project settings change? 

Since the user would be working on a copy of the original `*.sample.pbb` file he/she won't be able to detect any changes in the sample project. Just relying on a sample project to be copied might not be a good enough solution.

### Add Compiler Directive to Main Sources

So, I started reasoning that the best way to enforce compiler settings is via compiler directives in the main source file that check whether the compiler is set to threadsafe or not, console app or not, and so on with all required settings (XP, user mode, DPI awareness, etc.) and raise a `CompilerError` in case the settings are not as required.

This would be the strongest assurance that every project is compiled as it was intended, and the `*.sample.pbb` file would then be just a convenience to associate all source files to the projects (which is good, since there are many files in the IDE project), but would not require to store sensitive compiler settings nor user machine specific data. And if the main project was to every require different compiler settings, by changing the compiler directives mentioned above we would be sure that end users will get notified, even if they don't recreate their project file from the `*.sample.pbb` file.

**Comment by tajmone** [comment]
@SicroAtGit, I remember that you've already created a similar tool to check if PB source files contain IDE settings, for the __[PureBasic CodeArchiv Rebirth]__ project.

As you can see, many PRs to this project actually did contain sources with the IDE settings at their end (e.g. PRs #39 and #41). The problem is that it's all to easy to forget about them, because the settings are not shown by the PureBasic IDE.

So, I was hoping to add a tool that can validate all PB/SB sources in the repository, and add its execution to the Travis CI build test.

I can remember experimenting with it on the prototypes work repository:

- https://github.com/tajmone/PBCodeArcProto/blob/master/_tempwork/CodesCleaner.pb#L93

but that was quite a while ago. How is the current status of your validation tool? Is there a ready made tool that could be used, or do we need to readapt part of its code to extract this isolated functionality?

The validation tool should work on all OSs possibly, so end users can validate their files locally before submitting a PR, but for tesing on Travis CI we'll need to include a precompiled Linux x64 binary for Ubuntu (since we can't compile it from source on the Travis VM).

[PureBasic CodeArchiv Rebirth]: https://github.com/SicroAtGit/PureBasic-CodeArchiv-Rebirth

**Comment by tajmone** [comment]
I'm still undecided wether we should create a PB tool to validate the sources or not. Using PB forces us to add a precompiled binary (since Travis CI can't access the PB compiler online), whereas using a script or an open source language wouldn't require any binaries.

To check for the presence of IDE settings, it might be done with a GREP one-liner actually, because we only need to check for the presence of the `; IDE Options = PureBasic` line (which is always present when this setting is used).

So, unless we need to carry out some other validations, I could add this check to the current `validate.sh`.

The reason I was planning to use PB was because I would liked the validator to also check that the code is properly linted — in terms of indentation and lack of trailing whitespaces. 

Bare in mind that the current EditorConfig validation on Travis CI doesn't check PB sources for trailing whitespace, due to the fact that the IDE indents empty lines, which makes the EClint test fail. So I was thinking to add trailing spaces validation to the PB validator app, and also to reuse the formatter code from the IDE to reformat any modified files in a temporary folder and then compare them to the original files in the commit in order to check that they were properly reformatted via the PB IDE.

I noticed that various PR here contained PB sources that were not reformatted via the IDE, which resulted in hundreds of lines showing up as modified whereas only whitespace differed. This results in terrible diffs in the repo history, which are hard to read and track. So, I still think that enforcing PB sources validation at commit/PR time via Travis is required.

Maybe, I could start adding the GREP one-liner to the `validate.sh` script to start with, so we can prevent IDE settings from creeping in. Then we can decide how to to handle checking for source linting and trailing whitespaces later on, and whether to use PB for the task or some other scripting language.

Any ideas on possible solutions?

**Comment by kenmo-pb** [comment]
- @tajmone Yes, if you can, please check for `; IDE Options = ...` when validating submissions.
- I'm surprised that the linter doesn't have an option to allow indented whitespace lines. Maybe we do need a custom script to validate, and maybe in something more portable like Python instead of PB.
- About Compiler checks and CompilerError, yes let's definitely add those. I use those often to enforce build settings, especially after I stopped appending IDE settings to the end of source files.

About the git-unfriendly data saved in `pbp` files:
- Maybe projects need a new option like "Source Control friendly mode" (needs a better name) which would prevent all that user/system specific data from being saved.
- More drastic option: instead of giving the user a new option, just completely stop saving that data to any `pbp` files... is any of it really necessary? All I can think of is the "Files have been modified: ......" IDE warning.

**Comment by tajmone** [comment]
@kenmo-pb:

> I'm surprised that the linter doesn't have an option to allow indented whitespace lines.

The IDE formatter preserves indentation on empty lines, but it would be useful to have an option to enable/disable this. The problem is that the EditorConfig standard considers the whitespace on a line with only whitespace as _trailing whitespace_ instead of _indentation_:

- editorconfig/editorconfig#238

[I disagree with that choice], because (quoting myself from the above Issue):


> ... the problem lies with considering the whitespace in _indented empty lines_ as trailing whitespace. There is no trailing whitespace in empty lines, only indentation.
>
> The concept of _leading-_ and _trailing-_ whitespace is clearly in reference to actual contents being there. Since there is no representation of a line-beginning, but end-of-lines are indeed represented by the EOL sequence (which is also considered belonging to the whitespace category), when a line contains only whitespaces we're dealing with and indentation of the end-of-line — not trailing whitespace after the line beginning.
>
> This can be easily grasped by thinking of the problem in terms of RegExs, where the line beginning anchor `^` doesn't actually represent a real character in the text, whereas the end of line anchor `$` matches either `LF`/`CRLF` (or EOF).
>
> If empty lines with only whitespace where already interpreted this way, we wouldn't even need be asking for this new feature.


But still, it looks like EditorConfig is going is going to treat that as trailing whitespace, which means that we can't rely on  the EditorConfig validation via EClint on Travis CI for this regarding PB files. Hence the need for an extra tool or script.

> Maybe projects need a new option like "Source Control friendly mode" (needs a better name) which would prevent all that user/system specific data from being saved.

I though of that too, it would be really useful to be able to toggle between any custom settings and a set of predefined strict settings for version control — enforce the IDE default formatting settings (2 spaces indentation, etc.), and prevent any machine-specific info to be exposed to the version controlled sources.

> More drastic option: instead of giving the user a new option, just completely stop saving that data to any pbp files... is any of it really necessary? All I can think of is the "Files have been modified: ......" IDE warning.

Maybe a middle ground, e.g. keeping in the `.pbp` file all those settings which apply to any machine, and move user-specific settings and info (e.g. file changes timestamps and hashes, etc.) in a `.user.pbp` file, which can then be ignored in the repository. This would allow new versions of the IDE to be able to use old project files, by simply moving some info in the new  `<project name>.user.pbp` file that lives along the traditional  `<project name>.pbp`.

The problem is that to do this requires studying carefully how the various settings are stored in the XML project file, and all the possible combinations thereof. I had started to do this for the PBasmUI project:

- https://github.com/tajmone/PBasmUI/wiki/Compiler-Options-Mapping

but then gave up because I couldn't workout how to replicate the Windows info settings without going nuts (which is now easy to do, with the IDE being open sourced). You have to consider that there are some tricky settings to deal with, not only due to cross platform differences, but especially in how the IDE handles files which have settings of their own (in the source) and are also part of the project. Some combinations can get complex, and most are undocumented.

The idea is that it would be better to shift to a similar project file system that doesn't break forward compatibility of existing projects, and that could also provide an easy way to convert the new system into the old one (that's why using the same XML system but in split files might be wiser).

But then, maybe adopting an alternative project file altogether might be better for version control (especially if using YAML, TOML or JSON instead of XML, so it's human redable), but unless it becomes part of the official IDE it doesn't make much sense (it would just become one of the many cool PB projects and tools that went forgotten in time); and in any case it would still require to provide a two-way conversion tool between the old and new format (IMO).

So, it need to be thought well from the onset, considering all edge cases, and looks like a long-term project requiring considerable work. Most of all, if it's going to be included in the PB/SB official IDE, it needs to be discussed and approved beforehand (something that, frankly, should be done for any new features, instead of just presenting them out-of-the-blue as pull requests that were never even discussed).



[I disagree with that choice]: https://github.com/editorconfig/editorconfig/issues/238#issuecomment-564365201

**Comment by SicroAtGit** [comment]
For fun I started a Python script that already has the following features:

- Remove trailing whitespaces
- Preserve empty lines which contain indentations
- Remove PB settings at the end of the code
- Make sure that there is an empty line at the end of the code

`$ python Cleaner.py PBCodeFile.pb`

Interested? If so, I would like to publish the code under the MIT license.

**Comment by tajmone** [comment]
OK, PR #42 solves the problem of IDE settings ending up in the repository.

In the end, I've just used GREP for the task, so we can do all checks with a single Bash script that works on all platforms. When (if) the PR gets merged into `master` it will auto-close this Issue, when that happens I'll open another issue dedicated to handling PB/SB projects, and resume the relevant things that came up in this discussion.

We still have the problem of checking if the sources where reformatted via the IDE or not, which really helps to keep clean commits. Since we can't use EClint/EditorConfig for that, the only thing that comes to my mind is to check for trailing spaces at the end of non-empty lines via GREP — the rationale here being that the presence of a single trailing space would be a strong enough indicator that at least one PB source wasn't reformatted via the IDE native linter.

Any thoughts on this?

**Comment by tajmone** [comment]
@SicroAtGit:

> For fun I started a Python script that already has the following features:
> 
> - Remove trailing whitespaces
> - Preserve empty lines which contain indentations
> - Remove PB settings at the end of the code
> - Make sure that there is an empty line at the end of the code

That's really cool, thanks.

> If there are also trailing whitespaces in these lines, they are not removed.

Makes sense, tracking indentation size would add unneeded complexity.

So, this would be a code style fixer. This might come quite handy.

**Comment by kenmo-pb** [comment]
@tajmone Is it possible to whitelist files so they are *not* validated for IDE settings, trailing whitespace, etc.?

Why would I ask that?? Well, the IDE is using a 2014 version of STARGATE's TabBarGadget. The latest version is March 2019 and includes some improvements – although I'm not sure whether they affect the IDE usage (which is why I didn't open an issue).

It would be nice to keep the IDE up-to-date with the latest TabBarGadget, and it would be *extra* nice if the IDE used an exact unmodified copy. But right now, it would fail the validation script.

**Comment by tajmone** [comment]
> @tajmone Is it possible to whitelist files so they are not validated for IDE settings, trailing whitespace, etc.?

Yes, indeed it's possible. It only requires adding more file patterns in `.editorconfig`, _after_ the core rule, to override specific files or folders, by overriding the required settings with `=unset` (so that for those files EClint won't check for trailing whitespaces, or indentation, etc.).

If you provide me an example of the files that need to be skipped in the checks I can paste here a more practical example.

**Comment by tajmone** [comment]
Besided, this makes sense if it's code that is pasted from another project, since we don't expect anyone to edit its sources here but only upstream, for in that case code style checks are not really significant.
