### ISSUE TITLE
Orphan `Libmba` title in README.md

### ISSUE THREAD

**Issue by Naheulf** [fantaisie-software/purebasic#179]
I just found that [Libmba entry](https://github.com/fantaisie-software/purebasic/blob/0869d98a0d08f329c2dd3d79e43f8ee4b49bb52f/README.md?plain=1#L28) was not removed from README.md summary with #172.
However I think it don't worth it to create a new PR for only that.

**Comment by t-harter** [comment]
Thanks for the find. I have added a commit to remove it in #178 which is the final cleanup of all things C related.
