### ISSUE TITLE
Unlocking the Wiki

### ISSUE THREAD

**Issue by tajmone** [fantaisie-software/purebasic#18]
__Could you please unlock the Wiki for public editing?__ It can be used to further document the build process for the various OSs, provide tutorials with images, notes, etc., without cluttering the main repository. I see that on the PB Forums various posts are appearing on how compiler setup problems were solved, so it might be worth starting to collect them under an editable Wiki, in a well ordered manner (and keep the Build document in the repository more general).

Furthermore, may I ask you to __add me to the repository Collaborators?__ This would allow me to do some things that I currently can't:

- __Work on the Wiki via Git__ (the unlocked Wiki only allows online editing, or pulling its contents, but not pushing for non-Collaborators). This would allow me to add images, sub-foldered contents for multi-page tutorials, and handle better global search-&-replace operations on the Wiki.
- __Use the Dashboard__ to manage Projects (e.g. for long terms features) and Milestones.
- __Create an manage labels__ for Issues and PRs (which make topics navigation easier).
- __Self-assign to myself Issues__ with approved tasks that I propose.
- __Push PR branches directly upstream__ — which provides simpler access to their contents to maintainers, unlike PRs from a fork which are harder to pull-in.
- __Transfer ownership of some of my PB repos__ — e.g. the [PureBasic Repository Template] that I've created makes more sense to belong to the [Fantaisie Software] account/organization. Strange enough, you can't make an ownership transferral proposal to users whom are not your Collaborators.

Of course, _I won't_ do any changes directly on `master` branch (I've been collaborating on enough projects to know the ethics).

In any case, I suggest you protect the `master` branch in the Settings panel, to prevent accidents, including preventing force-pushes by Owners (I always use this setting to protect my own repository from my own accidental mistakes, for accidents do happen, and when the need comes I temporarily disable the force-push lock).

Ultimately, the hope is that in the future we might see more an more members of the PB community joining on GitHub to contribute, eventually leading to the creation of a "PureBasic" and a "SpiderBasic" organization, with Teams and roles assignments. Creating the conditions for this to happen might help it happen (of course, it's a long shot and could just be wishful thinking, and maybe in one year time we might see the same "usual suspects" here, but I'd like to think otherwise since the PB online community is well consolidated on the Forums).

Anyhow, GitHub offers some rather powerful features for Organizations and Teams, allowing to fine-tune roles and privileges (e.g. creating translators teams, and other specialized roles) and even assigning ownership to code (files and folders) so that reviews by code owners are required to merge/squash into master PRs with changes to the code they own. This is very useful to protect sensitive parts of the code that if badly edited could compromise the security of a tool, etc. — or just to prevent people from changing someone else's code without their green light, out of respect.

It's also possible to assign to each Collaborator specific branches where he/she can push contributions to.

[PureBasic Repository Template]: https://github.com/tajmone/purebasic-repository-template

[Fantaisie Software]: https://github.com/fantaisie-software

**Comment by fantaisie-software** [comment]
All done !

**Comment by tajmone** [comment]
Thank you! I've invited you as a Collaborator to a couple of my repositories, so then I can transfer their ownership to you.

**Comment by tajmone** [comment]
Did you receive the invitation links to become Collaborator on two PB repos I own?
If not, I can resend them.

Then I can proceed with transferal of ownership.
