### ISSUE TITLE
Add Repository Topics

### ISSUE THREAD

**Issue by tajmone** [fantaisie-software/purebasic#20]
@fantaisie-software, could you click on __Manage topics__ in the main repository page and add the following keywords (only the owner can edit topics):

    purebasic purebasic-ide spiderbasic spiderbasic-ide editor ide debugger

(see my fork: https://github.com/tajmone/purebasic)

This would increase visibility of the repository on GitHub, and hopefully lead to curated [`purebasic`][purebasic] and [`spiderbasic`][spiderbasic] topics (with descriptions and images) once these two keywords reach the minimum popularity threshold.

Unfortunately, [Topics Guidelines] against conflict of interest prevent owners of the project covered by topic to curate the topic itself:

> * Avoid conflicts of interest. Maintainers of a project cannot add a topic or collection for their own project. If a topic is popular enough to warrant inclusion, someone else will add or improve it.

But if enough PB/SB related projects include the keywords in their topics, these will eventually reach the popularity threshold and end up in GitHub Topics radar as needing a curator — and then PureBasic and SpiderBasic will be entitled to a curated Collection too.

[purebasic]: https://github.com/topics/purebasic
[spiderbasic]: https://github.com/topics/spiderbasic
[Topics Guidelines]: https://github.com/github/explore/blob/master/CONTRIBUTING.md#guidelines

**Comment by fantaisie-software** [comment]
Done
