### ISSUE TITLE
About dialog's copyright message not current

### ISSUE THREAD

**Issue by kpeters58** [fantaisie-software/purebasic#209]
The About dialog's copyright message is not current: As of beta 8, it still shows the year 2020.

Suggest adding code to keep it current, rather than having literals which require annual updates ...

**Comment by fantaisie-software** [comment]
Makes sense, I will change it

**Comment by Vivek789658** [comment]
import datetime

def get_current_year():
    return datetime.datetime.now().year

# Assuming your copyright message is a string
copyright_message = f"Copyright © 2020-{get_current_year()} Your Company Name"

# Now, use the updated copyright message in your About dialog

To automatically update the copyright year in your About dialog, you can use code that dynamically generates ... code in python
