### ISSUE TITLE
README: Add Credits and Acknowledgements

### ISSUE THREAD

**Issue by tajmone** [fantaisie-software/purebasic#21]
Add to main [`README.md`][README] a "Credits" and an "Acknowledgements" section mentioning authors and legal info of third party contributions and/or assets.

- [x] Add a __"Credits" section__ mentioning authors and legal info of third party assets and components:
    + [x] __Silk Icon Set__ — (in [`PureBasicIDE/data/SilkTheme/`][SilkTheme]):
        * [x] adapted by Timo Harter, based on the __[Silk icon set 1.3]__ by Mark James, [CC-BY-2.5] license.
- [x] Add an __"Acknowledgements" section__ crediting contributors to the original IDEs, the Debugger, the code base and other assets (quotations are from Documentation Acknowledgements):
    + [x] __PureBasic__:
        * [x] Timo 'Fr34k' Harter — "For the IDE, Debugger, many commands and the great ideas. PureBasic wouldn't be the same without him!"
        * [x] Danilo Krahn — "To have done an huge work on the editor and on the core command set, without forget the tons of nice suggestions about code optimization and size reduction... Thanks a lot."
        * [x] Gaetan Dupont-Panon — "For the wonderful new visual designer, which really rocks on Windows, Linux and OS&nbsp;X!"
    + [x] __PureBasic Logo__ — (in [`PureBasicIDE/data/logo/`][PB Logo]):
        * [x] Info inside the `.psd` files indicates it was designed by __GuShH__.
            - [x] ~~Get confirmation of paternity.~~
            - [x] GuShH created the 3D version of the original logo, created by Fred (see below).
            - [x] Credit GuShH for the 3D logo.
    + [x] __SpiderBasic__:
        * [x] ~~Andre Beer — "complete translation of the guides into German."~~
            - [x] omitted for now, since the guides are not included in the repository.
        * [x] Timo 'Fr34k' Harter — "for the IDE, Debugger, many commands and the great ideas."
        * [x] Gaetan Dupont-Panon — "For the wonderful new visual designer."
    + [x] __SpiderBasic Logo__ — (in [`PureBasicIDE/data/SpiderBasic/`][SB Logo]):
        * [x] Find out who designed it.
- [ ] __Profile Links__ — For all mentioned people, try to provide a link to their GitHub profile, PB Forum profile, or website (in order of priority).
    + Managed to trace back PB Forum profiles for most mentioned people except:
        * [x] Danilo Krahn:
            - [PB Forum](https://www.purebasic.fr/english/memberlist.php?mode=viewprofile&u=85)
            - [GitHub](https://github.com/D-a-n-i-l-o)
        * [ ] Fabien Laboureur
        * [x] Gaetan Dupont-Panon:
            - [PB Forum](https://www.purebasic.fr/english/memberlist.php?mode=viewprofile&u=186)

-------------------------------------------------------------------------------

### Notes

The "Credits" section is more on the legal side of crediting third party assets and their license terms; whereas the "Acknowledgements" section is more on the gratitude side toward all those who helped developing the contents found in this repository.

The main sources for the above information are:

- [PureBasic support page]
- [PureBasic Documentation » Acknowledgements]
- [SpiderBasic support page]
- [SpiderBasic Documentation » Acknowledgements]

Other info is gathered from the assets themselves (either their sources or attached documents).

[README]: ../blob/master/README.md
[PB Logo]: ../tree/master/PureBasicIDE/data/logo/
[SB Logo]: ../tree/master/PureBasicIDE/data/SpiderBasic/
[SilkTheme]: ../tree/master/PureBasicIDE/data/SilkTheme/

[PureBasic support page]: https://www.purebasic.com/support.php
[PureBasic Documentation » Acknowledgements]: https://www.purebasic.com/documentation/mainguide/greats.html

[SpiderBasic support page]: https://www.spiderbasic.com/support.php
[SpiderBasic Documentation » Acknowledgements]: https://www.spiderbasic.com/documentation/mainguide/greats.html

[Silk icon set 1.3]: http://www.famfamfam.com/lab/icons/silk/ "Visit the Silk Icons page at www.famfamfam.com"

[CC-BY-2.5]: https://creativecommons.org/licenses/by/2.5/ "Creative Commons Attribution 2.5 Generic"

**Comment by tajmone** [comment]
@fantaisie-software, I need some help getting some facts straight:

- [ ] Can you confirm that the PureBasic logo was designed by GuShH?
- [ ] Can you tell me who designed the SpiderBasic logo?

If you can think of any third parties and assets that should be mentioned either in Credits or Acknowledgements, in relation to the contents of this repository, please add them here.

I think it's important to duly credit historical contributors, and to honour third party assets license in the main README (not just in subfolders).

**Comment by fantaisie-software** [comment]
The PureBasic logo was designed by myself, but the '3D' version in .psd by GuShH
The SpiderBasic logo is designed by my brother, Fabien Laboureur

**Comment by tajmone** [comment]
> The PureBasic logo was designed by myself

How would you like to be mentioned in the README?

**Comment by tajmone** [comment]
@fantaisie-software:

> The PureBasic logo was designed by myself

The problem is that I have no clue about your nick on the PB Forums. If I understand correctly, here on GitHub @alphasnd is Fred, right? So, who's @fantaisie-software?

**Comment by tajmone** [comment]
> The SpiderBasic logo is designed by my brother, Fabien Laboureur

I guess then that both accounts are owned by Fred. I was confused by the double profile.

**Comment by fantaisie-software** [comment]
Yes, it's my both account, I will use only fantaisie-software here. You don't need to acknolegde me for my own logo..

**Comment by tajmone** [comment]
### Help Me With Contributors Links!

Does anyone know if Fabien Laboureur and Gaetan Dupont-Panon have a GitHub account, or which is their PB Forum user ID?

I wanted to add a link to their profiles when mentioning them in the various credits and acknowledgements, but wasn't able to find them neither on GitHub nor the PB Forum (if they have accounts there, they're probably using nicknames).

Otherwise, I might just close this issue and simply keep them mentioned by name, without back links (I did try, after all).

**Comment by SicroAtGit** [comment]
### Gaetan Dupont-Panon

PB help => Acknowledgements:
> - Benny 'Berikco' Sels: To provide an amazing first class Visual Designer for PureBasic. That's great to have such kind of help ! 
> - Gaetan Dupont-Panon: For the wonderful new visual designer, which really rocks on Windows, Linux and OS X !

Berikco (Tue Aug 31, 2010):
> I started Visual Designer with Fred
(https://www.purebasic.fr/english/viewtopic.php?p=332593#p332593)

Polo (Fri Aug 03, 2012):
> A free Form Designer for Purebasic Mac, Windows and Linux.
> The Form Designer is now integrated in the Purebasic IDE
(https://www.purebasic.fr/english/viewtopic.php?p=386444#p386444)

So I think that Gaetan Dupont-Panon is called [Polo](https://www.purebasic.fr/english/memberlist.php?mode=viewprofile&u=186) in the PB forum.

**Comment by tajmone** [comment]
> So I think that Gaetan Dupont-Panon is called Polo in the PB forum.

Thanks Sicro! I did come across "Polo" in a few threads, but wasn't 100% sure; also the profile doesn't say much. But your links dispel all confusion and doubts.
