### ISSUE TITLE
Achieving Full Git Compliance

### ISSUE THREAD

**Issue by tajmone** [fantaisie-software/purebasic#24]
In its current stage, this repository suffers from usage vs Git tracking problems — i.e. in order to use and build the IDE end users inevitably change parts of its contents, thus polluting the Git working directory and ultimately having to work in branches.

This is the invevitable consequence of opening to pubblic coolaboration a project that was (until now) handled by a small number of mainteners focusing on local building. Since fixing all these issues might involve multiple steps, I've created a Project for this task, which would allow better tracking of it ongoing status:

- __[Full Git Compliance]__ (&nbsp;_project_&nbsp;) — Make repo usable without affecting tracked contents.

Furthermore, I've spotted two different categories of problems affecting the integrity of the repository:

- _machine-specific settings_ — end users need to edit tracked configuration files in order to build the IDE.
- _PureBasic IDE inteference_ — (see #15 for more details and solutions):
    + some IDE configurations on the user machine could cause source files to be modified by injecting IDE settings at the end of the source file.
    + PB project files are modified when exiting the IDE, by embedding local info which is machine-specific.

For the above reasons, I've created two separate milestones for tracking these two independent aspects of general problem covered in the __[Full Git Compliance]__ project:

- __[machine agnosis]__ (&nbsp;_milestone_&nbsp;) — Strip build toolchain of machine-dependent settings.
- __[PB vs Git]__ (&nbsp;_milestone_&nbsp;) — Protect tracked contents from changes by PB IDE.

This is just my initial proposal (and can be easily undone), but if everyone is OK with it we could use the Dashboard tools track the overall goal status by splitting it into invididual Issues per task, using milestones and the Project ([automated kanban with review]) to simplify tracking the whole thing via cross-refereces.

This issue could serve as the general discussion thread, to evaluate pros and cons and agree on individual steps, so we can create specific Issues to track each one of them.

### References

- __[Full Git Compliance]__ (&nbsp;_project_&nbsp;):
    + __[machine agnosis]__ (&nbsp;_milestone_&nbsp;)
    + __[PB vs Git]__ (&nbsp;_milestone_&nbsp;)

[Full Git Compliance]: https://github.com/fantaisie-software/purebasic/projects/1 "Go to the Project dashboard"
[PB vs Git]: https://github.com/fantaisie-software/purebasic/milestone/2 "Go to the milestone page"
[machine agnosis]: https://github.com/fantaisie-software/purebasic/milestone/1 "Go to the milestone page"
[automated kanban with review]: https://help.github.com/en/github/managing-your-work-on-github/about-project-boards "Learn more about project boards on GitHub Help"

**Comment by fantaisie-software** [comment]
I think we are going nice for now, and we should may be slow down the work to make the repo better and actually wait and see if it gets used :).

I also think we will need to actually change the IDE to handle better GitHub and versionning in general (for example splitting the .PBP into 2 files, one which is common for all projects and another one which has only user specific changes).

**Comment by tajmone** [comment]
> I think we are going nice for now, and we should may be slow down the work to make the repo better and actually wait and see if it gets used :).

Sure, we don't have any deadlines hanging on our heads, the purpose of setting goals is just for long term planning, but we all contribute when we have time.

But I do think that managing to shape the project for coordinated usability is of essence. As for whether it gets used or not, probably much also depends on how accessible and documented it becomes, so it's worth investing energy in that direction. Of course, none of this guarantees affluence of contributors, but it can definitely aid those who do work on/with it, no matter how few — and it's also true that usually, people start walking in the kitchen when they can smell that the food is ready, not before.

Keep in mind that, besides improving the IDE, this repository is also useful for creating other PB tools relying on these sources — from syntax highlighters being able to obtain an always up to date list of keywords, to editors plug-ins which could reuse the code formatter for linting, and other parts of the code like adding Win specific version info to the compiled binaries, etc. 

There are actually a number of PB related projects and/or repositories which are going stale due to difficulties in updating assets which have to be manually fetched and re-adapted; suddenly having an official reference source accessible through version control is breaking news for these projects, which can now rely on it to keep assets aligned with the latest PB version.

> I also think we will need to actually change the IDE to handle better GitHub and versionning in general (for example splitting the .PBP into 2 files, one which is common for all projects and another one which has only user specific changes).

Maybe we should create a `devel` branch for all user contributions and changes, and merge back into master only when the changes are well tested and ready to be integrated in the actual IDE of the PB package — right now this might not matter too much, but ideally the `master` branch should always contain the sources matching the current PB release (eventually, release tags could be created on each PB/SB release).

This would provide freedom to contributors in preparing their work, but at the same time allowing others to see what's being prepared in the back stages, and when these changes are ready then PRs can be created and maintainers can be called in for code reviews. This would optimize everyone's time and still provide a centralized schedule of what's going on, via projects, milestones, issues, etc.

**Comment by fantaisie-software** [comment]
I was planning to tag master at every release, so we get a track of the history and can get back to a specific version. About the 'devel' branch, it sounds good.

**Comment by kenmo-pb** [comment]
I agree, please create a `dev` or `devel` or `development` branch and I will pull-request new features there, instead of cluttering up `master` 👍

**Comment by kenmo-pb** [comment]
Should we add the `Build/` folder to `.gitignore` ?

**Comment by tajmone** [comment]
> Should we add the `Build/` folder to `.gitignore` ?

Definitely yes. That and patterns to cover any other artefacts of the various build chains (all OSs).
