### ISSUE TITLE
ToolsPanel with auto-hide does not respect DPI settings when hit-testing

### ISSUE THREAD

**Issue by yuki-pb** [fantaisie-software/purebasic#252]
## Platform

**PB:** 6.03 LTS beta 10 (145f8e74652a) (**Note:** I believe any DPI-enabled IDE version suffers the problem.)
**OS:** Windows 11, x64

## What's the problem?

When the ToolsPanel is in auto-hide mode, and the system is configured with non-100% DPI scaling, the region you must mouse-over in order to show the panel is incorrect.

Because the hit-testing region compares physical coordinates against logical coordinates, the ToolsPanel can be considered hovered-over far before the mouse is near it.

This can disrupt editing as the panel appearing can overlap code a user is trying to select. Also, when returning to the hidden state, the editor flickers, which can be jarring (especially given dark themes).

Below is a video demonstrating the problem:

https://github.com/fantaisie-software/purebasic/assets/127664937/0133ae9b-82ba-4673-b77a-2ad3da44aefc

## What is the expected behaviour?

The IDE should only show an auto-hidden ToolsPanel when the mouse actually hovers over it.

Below is a video demonstrating expected behaviour:

https://github.com/fantaisie-software/purebasic/assets/127664937/c7d5c076-5ec0-4a44-95d6-c303345ad390

## Why does this happen?

This bug stems from the following logic in the ToolsPanel auto-hide hit-test procedure:
https://github.com/fantaisie-software/purebasic/blob/145f8e74652a0323bc153f5cf60d63595959245c/PureBasicIDE/ToolsPanel.pb#L412-L426

The `MouseX` value returned from `WindowMouseX(#WINDOW_Main)` is measured in physical pixels, while both `EditorWindowWidth` and `ToolsPanelWidth` are measured in logical pixels. By mixing physical and logical pixels in comparisons and arithmetic, we see unexpected results.

## Solution

A simple solution would involve converting the physical X-coordinate to logical coordinate respecting the applied DPI scaling before comparing against other logical coordinates.

The [`DesktopUnscaledX(...)`](https://www.purebasic.com/documentation/desktop/desktopunscaledx.html) function should suffice to handle the needed conversion.

**Comment by yuki-pb** [comment]
**Potential fix:** https://github.com/yuki-pb/purebasic/commit/d5d72a6c4c7843e236a26a0d15743d36d8cf8903

**Comment by yuki-pb** [comment]
**Related:** below is a better look at the flickering I was hinting at.

https://github.com/fantaisie-software/purebasic/assets/127664937/41c0f45b-2a81-41a0-8131-21ad0a8f479c

This happens to me ~90% of the time I hide the ToolsPanel, and it's sort of jarring given the dark theme I use.

I have a workaround for it here: https://github.com/yuki-pb/purebasic/commit/6d88edbf38e9b810a673b24ccb3fe9585b6623e5 – it perfectly fixes flickering here and feels pretty great.

It might be somewhat of a hack, but I'm not familiar enough with `SliderGadget(...)` internals to know if the reparenting is otherwise possible without a risk of flicker.

Is this something the PB team would be open to including? Please do let me know if I should open an issue/PR for it. Similarly, feel free to PR from the commit I've linked if it looks good to you.

**Tested on:**
- **Windows 11, x64:** OK, flickering gone.
- **macOS 13.6, arm64:** OK, behaviour unchanged.
  - Note: there is slight judder on macOS, but this was already present in release.

**Comment by fantaisie-software** [comment]
Could you create a PR for your flicker fix as well ?

**Comment by yuki-pb** [comment]
> Could you create a PR for your flicker fix as well ?

Thanks !
PR created for flicker fix: #254

**Comment by fantaisie-software** [comment]
Fixed.
