### ISSUE TITLE
DocMaker doesn't translate some words

### ISSUE THREAD

**Issue by webarion** [fantaisie-software/purebasic#269]
Looking through this code, I couldn't find the DocMaker code anywhere. So my question is, is this closed source?
I would like to create a translation of my language so that
All words were translated using DocMaker. But I discovered that it is impossible to translate all the words because some words are hardcoded inside DocMaker. This makes translation into all other languages ​​illogical.
For example, I haven't discovered how to translate the @Overview  key, which is shown in the documentation as **Overview**

**Comment by webarion** [comment]
I hope that the author of DocMaker does not have racist beliefs and is ready to provide the opportunity for an absolutely complete translation into any language of this world.

**Comment by tajmone** [comment]
> I hope that the author of DocMaker does not have racist beliefs and is ready to provide the opportunity for an absolutely complete translation into any language of this world.

What has language got to do with race? Your comment is out of place, the accusation of racism is quite offensive.

**Comment by fantaisie-software** [comment]
> I hope that the author of DocMaker does not have racist beliefs and is ready to provide the opportunity for an absolutely complete translation into any language of this world.

If you think talking trash will get you somewhere here, I can tell you it won't. Topic closed.

**Comment by webarion** [comment]
This is not chatter, but an attempt on my part to understand why you did what you did. And this is really initially offensive. Why did a smart person do this?
This suggests that there is bias here.

Why do you answer so rudely, not understanding that I was not trying to offend anyone.

And I have no such desire to offend anyone.
But, I really don’t understand why, in a closed code for translation of help, you hard-coded words that can only be translated into a few languages, leaving everyone else without such an opportunity?

**Comment by webarion** [comment]
> What has language got to do with race? Your comment is out of place, the accusation of racism is quite offensive.
You misunderstood my words. There is no accusation in my words!
The human brain is also a programmable environment. And the ability to speak is software. If you are a programmer, try to inspect the code of my words, and you will understand that in these words there is no desire to offend, and in my words there is no desire to accuse.
And this is all just because I don’t understand why smart people make illogical programs.
