### ISSUE TITLE
Wiki: Add License

### ISSUE THREAD

**Issue by tajmone** [fantaisie-software/purebasic#27]
I'm currently working on the `CONTRIBUTING.md` document locally, and I realized that we need to clarify the license implication of contents submitted to the Wiki, to avoid misunderstanding — especially if submitted contents might be reused in the PureBasic/SpiderBasic documentation, forums, or the main repository.

One could argue that the Wiki being part of the project falls under the same license terms, but it's always better to be clear about licenses.

Among the various options that come to my mind are:

1. Explicitly stating that the Wiki has the same dual license of the repo.
2. Adopting __[CC-BY-SA-4.0]__ for the Wiki.
3. Adopting the __[Fantaisie Software License]__ (only) for the Wiki.

The problem with choices 1 and 2 is that both __GPL__ and __[Fantaisie Software License]__ are designed for software, not text — the latter even more so:

```
                FANTAISIE SOFTWARE LICENSE
                Version 1, 26 November 2019

By contributing modifications or additions to these software, you grant
a perpetual right to Fantaisie Software to use, modify and distribute your
work in the PureBasic package.
```

Choice 2  (__Creative Commons Attribution Share Alike 4.0 International__) seems better because it's a license designed for creative works like text, images, etc., rather than code. Also, version 4 of the __CC-BY-SA__ was updated [to make it compatible with __GPLv3__], so that any contents released under __[CC-BY-SA-4.0]__ license can be included in a __GPLv3__ project and its terms are automatically fulfilled by the latter (no need to also include the __[CC-BY-SA-4.0]__ license in the project).

Whichever way, it's important to be transparent regarding the legal implications of contents submitted by third party volunteers, to avoid potential misunderstanding and resentments.

[CC-BY-SA-4.0]: https://choosealicense.com/licenses/cc-by-sa-4.0/
[Creative Commons]: https://creativecommons.org/ "Visit Creative Commons website"
[Fantaisie Software License]: https://github.com/fantaisie-software/purebasic/blob/master/LICENSE-FANTAISIE
[to make it compatible with __GPLv3__]: https://wiki.creativecommons.org/wiki/ShareAlike_compatibility:_GPLv3#How_one-compatibility_operates "Read more about CC-BY-SA-4.0 and GPLv3 compatibility"

**Comment by fantaisie-software** [comment]
CC-BY-SA-4.0 seems good for Wiki, it's a community project after all. I guess it could still be included in PB package, right ?

**Comment by tajmone** [comment]
> I guess it could still be included in PB package, right ?

My understanding is that YES, it should be doable even without the __[Fantaisie License]__ addition to the Wiki — yet, it might be a __good precaution__ to also include the latter in the Wiki in view of Wiki contents reuse in the official packages, because of the intermediate step from the Wiki to the repository. 

Below I include are some notes I had gathered while preparing this Issue...

From [choosealicense.com](https://choosealicense.com/licenses/cc-by-sa-4.0/):

|  permissions:  |    conditions:    |  limitations: |
|----------------|-------------------|---------------|
| commercial-use | include-copyright | liability     |
| modifications  | document-changes  | trademark-use |
| distribution   | same-license      | patent-use    |
| private-use    |                   | warranty      |


### GPLv3 Compatibility With CC-BY-SA-4.0

The __CC-BY-SA__ v4.0 and the GPL v3 were both designed to be compatible with each other, and __[CC-BY-SA-4.0]__ contents can always be included in a __GPLv3__ project with its terms being fulfilled by the __GPLv3__ license — [from Creative Commons Wiki](https://wiki.creativecommons.org/wiki/ShareAlike_compatibility:_GPLv3#How_one-compatibility_operates) (italics mine):

> When someone creates an adaptation of a BY-SA licensed work and includes it in a GPLv3-licensed project, both licenses apply and downstream users must comply with both licenses. However, Section 2(a)(5)(B) of BY-SA 4.0 allows anyone who receives the adapted material downstream to _satisfy the conditions of both BY-SA and GPLv3_ (i.e. attribution and ShareAlike) _in the manner dictated by the GPLv3_.

So, having the Wiki under __[CC-BY-SA-4.0]__ should allow reusing its contents in the main repository directly, with the GPLv3 license being sufficient to honour the conditions of the __[CC-BY-SA-4.0]__.

But you need to be careful here about the extra passage from the repository to the packages, which is not necessarily covered by the Wiki __[CC-BY-SA-4.0]__ license alone.

* The compatibility of __CC-BY-SA-4.0__ and __GPLv3__ was intentionally designed by their license drafters through a careful and mutually agreed revision of both license in view of that compatibility goal. 
* Even with the compatibility status — allowing __CC-BY-SA-4.0__ contents to be included in a __GPLv3__ project without the need of adding also the former license — there are still some differences between the two licenses, for the former was designed with contents other than code in mind, while the latter was crafted around source code.
* The addition of the __Fantaisie License__ terms to the repository doesn't directly affect the Wiki, unless you explicitly add a dual licensing to the Wiki too.
* Compatibility between the __Fantaisie License__ and __GPLv3__ is one thing, and its compatibility with __CC-BY-SA-4.0__ is a separate thing (which needs to be investigated).

### This Repo vs PB Packages

Now, having said that, I'm not a lawyer and legal matters are prone to hair-splitting interpretation in real courts. Add to that:

- GPL licenses are quite complex to understand to begin with.
- Open source licenses, in general, were designed in the void realm of good intentions, but haven't been thoroughly tested in real court-case scenarios.
- Each country is likely to interpret differently the terms of any license, based on the local jurisprudence principles.

Finally there's the extra complication layer of adding the __[Fantaisie License]__ on top of the __GPLv3__ terms, and now also the __CC-BY-SA-4.0__ terms. Both licenses define restrictions that can't be overruled, so dual licensing is a bit of a tricky thing anyhow.

Besides, any contents contributed or modified in this repository will need to fulfil the __GPLv3__ terms in the packages — the_ "perpetual right to Fantaisie Software to use, modify and distribute"_ contributed work to the repository into the PureBasic package would still have to abide to the  conditions set out by __GPLv3__ regarding mentioning paternity, copyright, etc. — all of which are blurred out by the very Git context, where users contribute to a project which is licensed to the project creator, and the fact that in a Wiki there is no real "author", due to text being collaboratively edited and belonging to the project.

I'm not a lawyer but I know that when a legal dispute ends up in court, lawyers will try to climb on glass, clutch at straws and split hairs to win their case — examining every word of a license under the microscope, ad debating over semantics to bend interpretations toward their goals.  Ultimately, license are a form of contract, and contracts are based on words and how we interpret them.

#### Fantaisie License Terms

Technically speaking, the __[Fantaisie License]__ only covers the PureBasic package:

```
                FANTAISIE SOFTWARE LICENSE
                Version 1, 26 November 2019

By contributing modifications or additions to these software, you grant 
a perpetual right to Fantaisie Software to use, modify and distribute your
work in the PureBasic package.
```

So a judge could argue that it doesn't cover contents inclusion into the SpiderBasic package, which would then be fully subjected to the __GPLv3__ terms only.

Also, the license text only mentions explicitly "software", which might or might not cover the Wiki contents (or other documents), depending on how a court would interpret it. 

Words like "software" and "source code" are always the shady part in most open source licenses, for they leave to interpretation whether documentation should fall under those terms or not (one could argue that markdown is a syntax, therefore markdown files are source code). Most revisions and updates to FOSS licenses were the results of these ambiguities, trying to fix the problem with hindsight.

The fact is that some licenses were devised for source code, other for written texts, images and artwork in general. The fact that source code file often include parts of the documentation into their comments (or vice versa, in case of literate programming) further blurs the division line between code and documentation. Also, most software packages are released with a single license, regardless of any documentation files that ship with it; and most likely similar well established practices would be considered in any legal dispute, for they are being accepted by developers and end users alike as the norm. 

Personally, I like to think that within the PureBasic community none of the above should really be a problem, and that users contributing to this repo and its Wiki are well aware of how contributed contents are going to be used (and even eager to see their changes make it into the package). But of course, that's wishful thinking and is hardly a real argument in court.

### Reference Links

See also:

- [ShareAlike compatibility analysis: GPL](https://wiki.creativecommons.org/wiki/ShareAlike_compatibility_analysis:_GPL)
- [ShareAlike compatibility: GPLv3](https://wiki.creativecommons.org/wiki/ShareAlike_compatibility:_GPLv3#Considerations_for_adapters_applying_the_GPLv3)



["three-layers" of restrictions]: https://creativecommons.org/licenses/#layers "Learn more about the three 'layers' of CC licenses"
[CC-BY-SA-4.0]: https://choosealicense.com/licenses/cc-by-sa-4.0/
[Creative Commons]: https://creativecommons.org/ "Visit Creative Commons website"
[Fantaisie License]: https://github.com/fantaisie-software/purebasic/blob/master/LICENSE-FANTAISIE

**Comment by fantaisie-software** [comment]
Don't overthink all this, I think it's fine like this.

**Comment by tajmone** [comment]
> Don't overthink all this, I think it's fine like this.

I totally agree, was just being cautious when it comes to legal matters, since the name of the Fantaisie company is a stake here.

I propose to add to the Wiki Home page the following section, plain and simple:


-------------------------------------------------------------------------------


# License Terms

Contents of this Wiki are subject to the [CC-BY-SA-4.0] license, and you are free to reuse them according to its terms.

By contributing to this Wiki you acknowledge and accept that your contributed material will also fall under the same [CC-BY-SA-4.0] license terms, and that [Fantaisie Software] is authorized to reuse them (in their original form or adpated) in its products (see the [Fantaisie Software License]).

The goal of the __[PureBasic OpenSource Projects]__ is to open source parts of [PureBasic] and [SpiderBasic] software in order to allow its users to contribute to the products' devlopment and its documentation, in the collaborative spirit that pervades the online community that was built around the PureBasic language in over two decades.

Any third party contents and assets included in this Wiki must be compatible with the [CC-BY-SA-4.0] license, and shall retain its original license.

-------------------------------------------------------------------------------

But I'll rather wait for your green light on this, since legal matters are always delicate.



[CC-BY-SA-4.0]: https://choosealicense.com/licenses/cc-by-sa-4.0/
[Creative Commons]: https://creativecommons.org/ "Visit Creative Commons website"
[Fantaisie Software License]: https://github.com/fantaisie-software/purebasic/blob/master/LICENSE-FANTAISIE

**Comment by fantaisie-software** [comment]
OK for me. Could you amend the FANTAISIE-LICENSE to remove the quote  "in the PureBasic package". You're right on this, it will disallow SpiderBasic (even if as all is GPLed it shouldn't be a problem to include it anyway).

**Comment by tajmone** [comment]
> Could you amend the FANTAISIE-LICENSE to remove the quote "in the PureBasic package". You're right on this, it will disallow SpiderBasic.

Would this be fine?

```
                FANTAISIE SOFTWARE LICENSE
                Version 2, 17 December 2019

By contributing modifications or additions to this project, you grant
a perpetual right to Fantaisie Software to use, modify and distribute your
work in its products and packages.
```

Compared to the original:

```
                FANTAISIE SOFTWARE LICENSE
                Version 1, 26 November 2019

By contributing modifications or additions to these software, you grant
a perpetual right to Fantaisie Software to use, modify and distribute your
work in the PureBasic package.
```


- _software_ &rarr; _project_ — so it covers also contributions to documentation, Wiki contents, etc.
- _PureBasic package_ &rarr; _products and packages_ — which covers also SpiderBasic, any future software and also the the PB Forums, the blog, etc. (which are products of Fantaisie Software too).
- _Version 1_ &rarr; _Version 2_.

> (even if as all is GPLed it shouldn't be a problem to include it anyway)

It shouldn't, adding clauses to contracts is fine — and in the worst case scenario they'd be simply dismissed, without invalidating the whole agreement.

**Comment by fantaisie-software** [comment]
Perfect ! Feel free to merge, I will close the issue

**Comment by tajmone** [comment]
Done! I didn't create a PR but merged and pushed directly. The branch is still there in case it's need to undo anything lossleslly.

**Comment by tajmone** [comment]
@fantaisie-software, I've added the licenses badges and the terms for contributed contents, as agreed above. Just wanted to let you know so you can check that everything is fine.

Now I'm able to finish the CONTRIBUTING document, which should be added to the repo soon.

**Comment by tajmone** [comment]
@fantaisie-software, can the `fantaisie` branch be deleted now? If all changes are good to good we can get rid of it (just left it there as a precaution).

**Comment by fantaisie-software** [comment]
Done
