### ISSUE TITLE
UnxUtils Alternatives

### ISSUE THREAD

**Issue by tajmone** [fantaisie-software/purebasic#30]
The [UnxUtils] package is really old and outdated — the 2007 date shown on SourceForge only refers to the date UnxUtils was _moved_ to SourceForge, but the actual contents were created between 1999 and 2003, therefore most tools are lagging far behind their Linux counterparts.

Many of the UnxUtils tools will no longer work on modern Windows as they were created for Windows 95 or XP — some tools report via `--help` that they were compiled using MS VC 5.0!

From a security point of view, UnxUtils is _extremely_ unsafe to use.

Add to this that the UnxUtils package doesn't even contain a copy of the GPL license — which says it all on the commitment of its author toward the GNU philosophy — and that the project was never updated on SourceForge (it's basically dead).

A significant number of the UnxUtils tools are now natively included in Windows 10, many others are already available in the [mintty]-based Bash that ships with [Git for Windows].

The real question is, _Which are the tools needed to build the IDE?_ Surely we won't need all the 123 tools of the UnxUtils package. Probably only the Make tools are needed, and a few others which might not be included in the Git Bash.

I suggest we assume that anyone interested in this repository will also have installed Git for Windows, and therefore has already access to the Bash and its most common tools.

We should then:

- [x] Create a list of the required tools to build the IDE which are missing in Git Bash.
- [x] Find their latest Windows x86 ports (Cygwin of MinGW are both fine).
- [x] Create a standalone Zip package with these tools (and their license files) and drop it the project Wiki, were it becomes available for download without cluttering the repository.

This way we could provide end user with a download link to a Zip file containing all the required tools to build the IDE under Windows OS — which is much better than a long list of instructions on how to download and setup these tools.

[UnxUtils]: http://unxutils.sourceforge.net "UnxUtils website"
[Git for Windows]: https://gitforwindows.org "Git for Windows website"
[mintty]: https://mintty.github.io/

**Comment by fantaisie-software** [comment]
Please don't get into this :). The IDE is only a very small portion of our whole build system and all is based on UnxUtils which works as expected on Win10. May be some tools in it are outdated and broken but we don't use them anyway so it's not a biggie.

That said I'm OK to provide a zip with only the needed tools to build the IDE

**Comment by kenmo-pb** [comment]
It does not *have* to be UnxUtils, does it? Maybe just change it to a suggestion: install UnxUtils *or* equivalent Windows ports of those tools. Later add links to alternates.

According to ChrisR on the forum, only `make`, `pwd`, `rm`, `touch`, `zip`, `cp` are required.

**Comment by tajmone** [comment]
> Please don't get into this :). The IDE is only a very small portion of our whole build system and all is based on UnxUtils which works as expected on Win10. 

My worry is that some end users (out of trust) might just add the UnxUtils bins folder to their PATH permanently — and this _would_ be a problem, because many of those commands have the same name of some CMD commands, and would end up replacing system command (and as it happens, some of these were reported as broken). 

I've gone through the users' feedbacks in the SForge project's comments and found various warnings about problems they've experienced. Older comments were positive, but later ones tend to show problems due to ageing and lack of compatibility with newer Win features.
 
> May be some tools in it are outdated and broken but we don't use them anyway so it's not a biggie.

I would be surprised if they'd still work in a year from now, as Windows in the past years has started to block execution of old software (just think of the `.hlp` files, which are blocked no matter the effort and attempts to use old tools to open them) and started blocking obsolete protocols (like SMB Shares used by NAS drives).

The sheer fact that the project doesn't contain the GPL license (doesn't even _mention_ it!) is a _biggie_ by itself and makes me uncomfortable. Sure, it's a project dating back to 2000, and at that time everyone was laxed about FOSS licenses (we all were) for they were still something new for the general public, and mostly misunderstood.

The whole point is that today we can easily find modern and up-to-date replacements for these GNU tools, and we don't really care if they are native or use the Cygwin DLL compatibility layers, as long as they do their temporary task. Also, 123 tools are too many, we should just hand-pick add what is needed.

> That said I'm OK to provide a zip with only the needed tools to build the IDE

Thanks, I think this is the best solution.

**Comment by tajmone** [comment]
@kenmo-pb:

> Maybe just change it to a suggestion: install UnxUtils or equivalent Windows ports of those tools.

What worries me is exactly the "install UnxUtils" part — which was never intended this was, but just to add the to the PATH for the build session. I fear that many users (especially those who struggle with English) will end up permanently adding UnxUtils to their systems — which, as mentioned above, would replace Windows system command like `find`, and others.

> According to ChrisR on the forum, only `make`, `pwd`, `rm`, `touch`, `zip`, `cp` are required.

Then only the Make tools and the `zip` commands needs to be provided for those who have installed Git, the rest is in the Bash already. The Make tools and other binutils can be easily found in any MinGW package today.

So we only need to work out exactly which command are required, and create a Zip with all the license and DLL dependencies. Maybe two packages, one for those who have installed Git and another for those who don't, so we don't override the Bash built-in tools.

I'll look into it and post my findings later on. 

Since I'm stuck in building the IDE due to the Win10 SDK problem, I'll need your help here @kenmo-pb, to confirm that the build process doesn't complaint about missing files.

(PS: I doubt that I'll ever solve the SDK problem, the best I can hope is using a VM to build the IDE, but I doubt my OEM Win license will work on a VM. So I might be in a dead end in this respect.)

**Comment by fantaisie-software** [comment]
> It does not _have_ to be UnxUtils, does it? 
>

Yes it does. Other bash/make are not exactly the same and doesn't behave correctly (we already tried to move from it)

**Comment by fantaisie-software** [comment]
About the SDK issue, I will give it a try

**Comment by tajmone** [comment]
> Yes it does. Other bash/make are not exactly the same and doesn't behave correctly (we already tried to move from it)

The UnxTools (without the update) uses GNU Make version 3.78.1 (1999), the `UnxUpdates.zip` contains GNU Make 3.80 (2002).

What happens exactly with newer versions of Make?

**Comment by tajmone** [comment]
I've checked my [MSYS2] shell, and it uses GNU Make 4.2.1 (2016), so there's a MAJOR version difference with UnxTools version. 

We might try to find a recently build Make package version 3.x, which should be compatible.

[MSYS2]: https://www.msys2.org/

**Comment by fantaisie-software** [comment]
It doesnt handle the Windows paths the same way (this version hanlde native path correctly, newer requiers a virtual path or something). You can try to just replace the 'make' tool and see what happen

**Comment by tajmone** [comment]
I've found these [Make for Windows] packages at [GnuWin] that contain GNU Make 3.81 (2006):

* [Binaries](http://gnuwin32.sourceforge.net/downlinks/make-bin-zip.php)
* [Dependencies](http://gnuwin32.sourceforge.net/downlinks/make-dep-zip.php)

This version is very close to the 3.78.1 version of UnxTools.

> It doesnt handle the Windows paths the same way (this version hanlde native path correctly, newer requiers a virtual path or something). You can try to just replace the 'make' tool and see what happen

I normally use the Make version that ships with mingw64-6.3.0 (Make 4.1, renamed as `\bin\mingw32-make.exe`), and it handles Windows paths correctly (as long as there are no spaces), whereas the Make that ships with MSYS2 doesn't. Maybe the difference is there. These are the links to the MinGW package I use (hosted at [Nim lang] website):

* [MingW 32 bit](https://nim-lang.org/download/mingw32.7z)
* [MingW 64 bit](https://nim-lang.org/download/mingw64.7z)

I thought that these path problems were tied to the POSIX layer of Cygwin DLL (in fact, the UnxTools was one of the few native GNU tools at the time, not using Cygwin), and that since most packages today use MinGW instead, the problem was gone (but then, in MSYS the problem is there, but that's a different case for it's an POSIX emulation environment on its own). I haven't used the version from GnuWin, so I've no idea how it handles paths.

I'll try and see if my father let's me carry out tests on his PC (he has the Win7 SDK installed), so I can actually try out the different versions myself.


[Nim lang]: https://nim-lang.org/
[GnuWin]: http://gnuwin32.sourceforge.net/
[Make for Windows]: http://gnuwin32.sourceforge.net/packages/make.htm

**Comment by fantaisie-software** [comment]
BTW, we use the lastest 'make' tool on Linux/OSX with the same makefiles, so except the paths issues, it should be OK

**Comment by tajmone** [comment]
> BTW, we use the lastest 'make' tool on Linux/OSX with the same makefiles, so except the paths issues, it should be OK

Then I think it's worth pursuing trying alternatives versions of Make for Windows.

Is not that we couldn't use the version from UnxTools for technical reasons — if it works it works, and Make is a tool which couldn't possibly do damage on the machine. The problem would be on the legal side: since UnxTolls doesn't fulfil the GPL conditions, taking from it and redistributing would be a legal issue — adding the GPL license to our package won't patch the situation, for any derivative product violating the license is illegitimate. One think is to link to the package, another is redistributing it (especially on a project tied to a company name, and doing it in a third party hosted service).

I hope I don't sound too tedious on legal matters, but _they do matter_ — as I said, I'm not a lawyer, but I do occasionally get called for expert contusing by a local law firm, and even write expert testimonies for them; so I have a good picture of the huge gap between on-line wishful discussions about licenses on programmers' forums and the harsh reality of how these unfold in real court cases. And, trust me, it's so big a difference that it makes it unworthy it to join the discussion. When they ask me for counsel, the first thing I ask is whether the expert witness of the counterpart is an actual programmer or not, because if he/she is then 99% we're going to win (we call it _professional deformation_). 

I usually don't like discussing license issues on-line, and avoid it unless it concerns directly a project I'm responsible for. The only reason I'm dropping here my two-cents advise is because I really have at heart PureBasic, but I don't wish to develop further the discussion on licenses — apparently everyone has his/her own interpretations of how licenses work, and usually these discussions are unfruitful, often taking a nasty direction. At least in court you get the satisfaction of being proven right by winning a case.

**Comment by ChrisRfr** [comment]
I uploaded on my fork the required Gnuwin32 tools to compile all the dependencies and the IDE.
I've included the licence files. All are grouped in a new Bin folder
https://github.com/ChrisRfr/purebasic/tree/master/Bin
They're a little outdated (less than UnxUtils) but they do the job

Thus, in Window-x64(x86).cmd, 
Set PATH=%~dp0\Bin;%PATH%
is sufficient, no need to download and use UnxUtils anymore

**Comment by tajmone** [comment]
> I uploaded on my fork the required Gnuwin32 tools to compile all the dependencies and the IDE. I've included the licence files. All are grouped in a new Bin folder
> 
> https://github.com/ChrisRfr/purebasic/tree/master/Bin
> 
> They're a little outdated (less than UnxUtils) but they do the job

This is much better! now we have the tools with the licenses, not from the jurassic era, and only what's needed.

> Thus, in Window-x64(x86).cmd,
> 
>     Set PATH=%~dp0\Bin;%PATH%
> 
> is sufficient, no need to download and use UnxUtils anymore

No need, Win users can download this package instead, from the project Wiki, so we don't pollute the repository with binary files (especially unneeded files by users from other OSs).

I think we'll have to create two separate Zip files, one without the common Bash commands (for those who have Bash because of Git, which is the majority of users) and another one (or a supplement?) for those who don't have Bash (and neither Git).

The script could also offer end users the option to download the zip package via cURL, which now ships natively with Win 10, but then I'm not sure about older versions like 7 and 8 (no one still uses Vista, I hope). If not, cURL becomes only a further complication (of course, the Git Bash also includes  cRUL, actually a better version from MS cURL, which is feature-incomplete).

Today I might not find the time, but when I have some spare time out the frenzy of these pre-festivity days I'll add your branch to my workflow so I can join in on experimenting with the script (right now I've just been pasting it from this Issue).

**Comment by tajmone** [comment]
@ChrisRfr, could you please do a couple of things on your ChrisRfr/purebasic fork, so I can join you in testing and developing the new script:

- enable Issues on your fork, from the Settings panel, so we can create discussion threads on your repo (no need to clutter the main project for preparatory and polish work, once it's ready you'll create the pull request anyhow).
- branch out the current work (which now is in `master`) so I can pull-it into my own workflow without having to do fiddle with asymmetric remotes (after all, you'll need to branch out if you want to create a PR on the main repo).
- I suggest (but it's up to you) that after creating a new branch from your current edits on `master` you _hard reset_ `master` branch to the upstream repository, in order to be able to keep it in synch. Your edits will then be in the new branch only, so nothing is lost.

**Comment by ChrisRfr** [comment]
Well, I need to learn more about GitHub and how to collaborate in future, if I can.
But it'll be after my end of the year holidays.

I've recreated my fork and enable issues on it
Then, I added my changes in a new branch, pull request. I hope it's better now

The changes in Autorun-x86(x86).cmd are probably good to take, with
the support of both Windows (7.1) SDK and Windows 10 SDK
and few controls added, access rights, check if path exist
I don't think there's any need to go any further

I'll let you see for the Gnuwin32 binary files, Wiki,...
Happy holidays season :)

**Comment by tajmone** [comment]
## Wiki Updated

I've adde to the Wiki a section about usage of UnxUtils:

- [Wiki » Building on Windows](https://github.com/fantaisie-software/purebasic/wiki/Building-on-Windows#unix-and-gnu-tools)

It clarifies that the intended usage is confined to the CMD session of building the IDE, and not adding them permanently to the system PATH.

I also mention that although in their time they were among the few fully-native Win32 ports of Unix commands and GNU tools, they are getting old and that there are other viable alternatives today.

**Comment by tajmone** [comment]
> Well, I need to learn more about GitHub and how to collaborate in future, if I can.
> But it'll be after my end of the year holidays.
>
> Happy holidays season :)


And to you, in case we won't see you back till then.

**Comment by t-harter** [comment]
You can also use Cygwin for the build tools. You just have to be careful with the paths:
- All paths that are handled by the build tools must use "/" instead of "\\" 
- It is best to avoid spaces and special characters.
- Paths that are only passed to VC or other Windows tools do not need to follow that

**Comment by tajmone** [comment]
> You can also use Cygwin for the build tools. 

That would add more dependencies (and a rather huge package too). I have MSYS2 on my machine (which is also required by Ruby for Windows), but from what I gather it won't work as smoothly as expected, especially if there are spaces involved in file paths, etc.

A simpler solution is using modern versions of the same tools of UnxUtils.

@ChrisRfr was preparing a new standalone package with the required Unix tools:

https://github.com/ChrisRfr/purebasic/tree/ChrisRfr-Build-SDK7-10/Bin

The package is almost ready, but still need to discuss a few details on the final distribution and get the green light from him (was waiting for @ChrisRfr to be back from the holidays, but still haven't heard since). Also, we'll need confirmation from @fantaisie-software to upload the ZIP archive with the tools to the Wiki and replace instructions for UnxUtils wit the new set of tools (but haven't heard from @fantaisie-software either since the holidays break).

Somehow, we're piling up pull requests and the repository is becoming stale.

**Comment by tajmone** [comment]
## New Unix Dependencies Package for Windows

I've uploaded to the Wiki the `UnixTools-4-Win.zip` archive containing the required Unix tools for building the PureBasic IDE.

- [`UnixTools-4-Win.zip`](https://github.com/fantaisie-software/purebasic/wiki/UnixTools-4-Win.zip)

The package was kindly created by @ChrisRfr (thanks Chris!), I've just added an html README file with a brief presentation and backlinks.

Now, @fantaisie-software if you can check the package and confirm that everything is fine with it, I suggest to:

- [ ] Replace any previous references to **UnxUtils** with a link to this new package, in the various build instructions in this repository ([`BUILD.md`][BUILD.md]) and the Wiki ([Building on Windows] page).
- [ ] Add a new Wiki page presenting this package.
- [ ] Mention @ChrisRfr contribution in the [Acknowledgements section] of main README.


[BUILD.md]: https://github.com/fantaisie-software/purebasic/blob/master/BUILD.md
[Building on Windows]: https://github.com/fantaisie-software/purebasic/wiki/Building-on-Windows
[Acknowledgements section]: https://github.com/fantaisie-software/purebasic/blob/master/README.md#acknowledgements

**Comment by tajmone** [comment]
@fantaisie-software?

**Comment by tajmone** [comment]
OK, I've created a PR with the above mentioned changes, referencing the new package by @ChrisRfr instead of UnxUtils.

I still need to update the Wiki page though (going to do that soon).

**Comment by tajmone** [comment]
### Wiki Updated!

See:

- https://github.com/fantaisie-software/purebasic/wiki/Building-on-Windows#unix-and-gnu-tools

I've also created some place-holder pages for the Lunx and macOS building instructions:

- https://github.com/fantaisie-software/purebasic/wiki/Building-on-Linux
- https://github.com/fantaisie-software/purebasic/wiki/Building-on-macOS

Hopefully someone will start documenting the build process for these OSs too.

Unfortunately, the Wiki hasn't seen any participation so far; maybe it should promoted a bit more on the Forum?

-----

@fantaisie-software, please check if all is fine (both in PR #72 and the Wiki changes), and close the issue if no further changes are required.
