### ISSUE TITLE
Typos in Settings Keys

### ISSUE THREAD

**Issue by tajmone** [fantaisie-software/purebasic#44]
PR #43 (in an attempt to fix all misspellings) revealed that there are some misspelled strings paired to IDE Settings keys. Fixing their spelling would break backward compatibility with user settings.

We should:

- [ ] __Add a warning comment__ next to those strings to prevent accidental changes (in the meantime).
- [ ] In comments that mention misspelled strings/keys, add a "`[sic]`" next to the misspelled word to indicate awareness of its misspelling status and that it should not be amended.
- [ ] Decide whether it's worth the effort to fix the spelling of these settings key.

There are possible workarounds to this, like introducing a double-mapping standard to handle the old misspelled keys, but they require adding some _ad hoc_ code (see [@kenmo-pb proposal] at PR #43).

Whether it's decided in favour or against tackling with similar fixes, this discussion might lead to a general rule regarding this type of interventions, which would be worth adding to the Contributors Guidelines (to prevent the same proposal coming up over and over again). 

[@kenmo-pb proposal]: https://github.com/fantaisie-software/purebasic/pull/43#issuecomment-572576399

**Comment by kenmo-pb** [comment]
@tajmone Good summary. Here are the misspelled keys I have found (but there could be more).

    NoIndependantColors
    NoIndependandColors
    AllreadyUsed
    PurifierIntervall
    GlobalIntervall
    LocalIntervall
    StringIntervall
    DynamicIntervall

Most of these are not in the *Preferences* but in the *Language* files, where it would be even *worse* to suddenly change keys.

If a preference key changes, OK, the default value will be used instead. The next save will fix the key.
*Actually - I realize right now - this might be a problem for users who switch back and forth between PB versions such as the LTS versions!*

If a language key changes, that's bad, because some strings won't be translated, and the IDE does not re-save and fix the keys like a `prefs` file!

Let's wait for Fred's opinion. I think these are very low priority. (Also we still need a development branch so we're not merging potential problems into `master`!)

**Comment by tajmone** [comment]
> Actually - I realize right now - this might be a problem for users who switch back and forth between PB versions such as the LTS versions!

In theory, users should be using the latest IDE to handle all projects since the IDE allows you to choose which compiler version to use, just like you can use the x64 IDE to compile 32-bit binaries (which is usually what you do anyway in order to compile the same project for both architectures using a single IDE session). At least, that's what I usually do. It only requires adding all the available PB packages to the preferences file via the IDE.

Latest version of the IDE are still capable of handling obsolete software settings (e.g. creating Ascii binaries) for the sake of using older PBCompiler versions. So, the IDE is already designed to be backward compatible, and we could reasonably argue that all users have the possibility of installing the latest version of PB.

But I understand that it could be a problem if one forgets about this, and that these fixes might introduce more problems that it's worth from a practical point of view. It ultimately boils down to how much one values language correctness. Personally, when I downloaded the trial version of PureBasic, these misspelling errors where one of the first things I noticed, and they had a negative impact on my first impressions on the product (they made it look an unkempt project, lacking attention to details).

Backward compatibility is a double-edged sword, on the one hand it grants projects continuity across evolution of the IDE, but on the other it could end up hooking the IDE for ever on these typos and other similar problems.

In the worst case scenario, this list of misspelled keys will be useful for fixing things in PureBasic 6 (whenever that is due).

> Let's wait for Fred's opinion. I think these are very low priority. 

Totally agree on both.

**Comment by fantaisie-software** [comment]
It doesn't worth the work to change it, let's call it history !

**Comment by tajmone** [comment]
> It doesn't worth the work to change it, let's call it history !

If we don't at least add some warning comments next to the mispelled strings that shouldn't be changed, we're going to face more fixes-attempts in the future!
