### ISSUE TITLE
New Keyboard Shortcuts

### ISSUE THREAD

**Issue by kenmo-pb** [fantaisie-software/purebasic#46]
I would like to collect a task list of all the Keyboard Shortcuts people would like to see added. Between myself, and the forums, I have these so far:

- [x] Delete Selected Line(s)
- [x] Duplicate Selected Line(s)
- [x] Move Selected Line(s) Up
- [x] Move Selected Line(s) Down
- [x] Zoom In
- [x] Zoom Out
- [x] Zoom Default / Reset
- [x] Paste as Comment

All of these I have implemented in my own PB/Scintilla projects, most are calls to built-in Scintilla actions. I have started to implement these in the IDE project. I would like to submit them once there is a `dev` branch so we don't clutter `master`.

I ask you all:

- Do you have more suggestions for shortcuts to be added?
- Do you think these belong as new Menu items, or with the "invisible" shortcuts listed at the bottom of the `Preferences > Shortcuts` (like "Select surrounding code block", etc.)?
- Any workaround for the ShortcutGadget displaying Up/Down/Left/Right wrong (it happens in `Preferences > Shortcuts`) as posted here: https://www.purebasic.fr/english/viewtopic.php?f=4&t=74310

Suggestions from the forum:

- [ ] Rename file (different from Save As)
- [ ] Show file in explorer
- [ ] Uppercase selection
- [ ] Lowercase selection
- [ ] Invert case selection

**Comment by fantaisie-software** [comment]
You can start with this list, it looks OK to me

**Comment by kenmo-pb** [comment]
I've implemented 5 of the listed shortcuts in PR #54 

The zoom functions will be slightly more complicated, because of synchronizing the zoom across all ScintillaGadgets (including on mousewheel-zoom, and on new Scintilla creation). But that's OK, I have implemented this before in my own projects.

Maybe the name of this issue should be *New Menu Items and Shortcuts* (not only shortcuts) because some of these belong in the main menu / popup menu. For example, on the forum there's a request for `Rename file` and `Show in folder` actions in the popup menu.  
https://www.purebasic.fr/english/viewtopic.php?f=3&t=74559

**Comment by kenmo-pb** [comment]
3 more shortcuts (zoom) merged in PR #62.

Added more forum suggestions above in first post.

**Comment by tajmone** [comment]
@kenmo-pb, to avoid dangling Issues which have already been fixed in PRs, please use [Autolinked references and URLs] in your commit messages, which simplify automatically tracking which commits/PRs relate to an Issue, and will automatically close the Issue once integrated.

I'm manually closing this since the task list is all checked and you mentioned having implemented all features in various PRs.



[Autolinked references and URLs]: https://docs.github.com/en/enterprise-server@3.0/github/writing-on-github/autolinked-references-and-urls
