### ISSUE TITLE
More spelling issues

### ISSUE THREAD

**Issue by kpeters58** [fantaisie-software/purebasic#55]
Nice work so far!

```
PureBasicDebugger/DebuggerGUI.pb  
; checks if an event is coming from a debugger window and dispactes it
```
That should be 'dispatches' it. I believe I also saw instances of 'childs' instead of 'children'

**Comment by SicroAtGit** [comment]
The pull request #56 fixes your mentioned misspellings :-)

**Comment by SicroAtGit** [comment]
I think this issue can be closed.
