### ISSUE TITLE
Adding PB Help Sources, Examples and the SDK

### ISSUE THREAD

**Issue by tajmone** [fantaisie-software/purebasic#61]
@fantaisie-software, I was wondering if this repo is going to include other assets beside the PB IDE, e.g. the Help Files, the code examples, and part of the SDK.

Personally, I'd love to contribute to the PB Help Documentation, which I understand is already publicly available via SVN (although it's an outdated version):

http://svn.purebasic.fr:8080/websvn/listing.php?repname=PureBasic+Public+SVN

I think it would make much more sense to have anything related to the PureBasic package under one single repository, so all the elements are in one place and refer to the same version — of course, by "all" I mean those parts which are intended to become open sourced.

This might require some structural re-organization of the repository, in order to accommodate all assets in independent sub-folders, and therefore would need to be carefully planned and announced in advance to avoid upsetting any contributors working on long-term features.

Ideally, we would have a directory structure like this:

```
/pb-ide/
/help/
    /images/
    /de/
    /en/
    /fr/
    ..          <- common assets to all locales
/sdk/
    /linux/     <- Linux specific assets
    /mac/       <- macOS specific assets
    /win/       <- Windows specific assets
    ..          <- common assets to all OSs
/examples/
    /linux/     <- Linux specific examples
    /mac/       <- macOS specific examples
    /win/       <- Windows specific examples
    ..          <- examples common to all OSs
```

Creation of the final distribution package should be easy to handle via custom scripts on your local production machine, and a similar structure would simplify both cross-platform contributions as well as OS-specific ones; the same goes for Help Files and its locales (which would also provide a solid base for anyone wishing to translate it to new languages).

Also, it would allow this repository to become a version controlled reference to obtain up to date assets like the SDK headers, PB applications required license files (with and without OGRE, plus Scintilla, PCRE, etc.), so that PB related projects could just add it as a Git sub-module and checkout the desired PB release tag to ensure inclusion of the right SDK headers, etc. (which currently requires manually copying and pasting the required files).

Besides, projects like the IDE, which require including the SDK files for its C dependencies, could import them directly from the `/sdk/` folders, avoiding assets redundancy in case more projects are added that use them.

As mentioned, my main area of interest would be the PB Help Docs, which I always wanted to contribute to (and attempted to do so in the past years, but to no avail).

I personally would discourage opening the gates to adding new contents to the PB documentation, because this would soon lead into wild directions and cause the different translations to diverge, and possibly introduce maintenance burdens. But the current documentation does indeed need some serious polishing (at least, the English version does), ranging from typo fixes to paragraphs rephrasing in order to make the text easier to read and less ambiguous in various places.

Another aspect of the documentation that might be improved is styles — at least, the Windows CHM file could do with some embellishment — although I suspect this could just as well apply to any documents that is (or could be) delivered as HTML files.

For example, once all the tools to create the CHM file (its index, TOC, and all) are in the repo, I'd like to consider adding syntax highlighting of the code examples and snippets to the build toolchain, which would make them not only nicer, but also easier to read — and since the IDE sources contain the updated list of all the PB/ASM keywords, it would be easier to ensure (via scripted automation) that the highlighter syntax definition is always up-to-date with the PB release the docs refer to.

There are many things that could be done to improve the documentation, not only for the Win CHM file but for all OSs. I work a lot with documentation and digital publishing (in all sorts of formats). As an example, here is my last published documentation (ported from Word to AsciiDoc), released just a week ago:

- https://tajmone.github.io/hugo-book/

That's the HTML version, created from AsciiDoc sources, with all source code syntax highlighted. The project is cross-platform and fully version controlled on GitHub, and the AsciiDoc sources can be converted to a variety of output formats, including PDF, man pages, CHM, ePub, and many others (I just didn't have the time to cover any of them, since the project is fresh, but have done so with other projects).

So, I really hope to soon see the Help files and part of the SDK being moved from the SVN to this repo — needless to say, I task I'm happy to take on if you give me the green light, and after having agreed on the new directory structure.

**Comment by fantaisie-software** [comment]
Yes, it's planned, but as we need to adapt all our build chain everytime we move a stuff (which takes time) it could be a bit later.

I agree than doc could be better so I will looking forward to it :)

**Comment by tajmone** [comment]
I agree, it has to be done a bit at the time, and each new folder will now further require to pass the code styles tests, so it's going to require reformatting and it'll be time consuming. Luckily it can be done in separate branches.

**Comment by tajmone** [comment]
@fantaisie-software, I really think that the Help sources should be added to the repo in order to keep the documentation in synch with all the new features that are flowing in (as mentioned in #79).

The PB Documentation was already lagging behind some language features _before_ open-sourcing the IDE via this repo; but now we're seeing new third-party features flowing into the IDE, but contributors are not able to also update the Help file accordingly.

The risk is that undocumented features might pile up beyond a manageable number, making it very hard to update the Help file to mirror the latest IDE. This includes not only updating the text, but also screenshots (e.g. whenever the Settings panel is updated with new options).

**Comment by fantaisie-software** [comment]
I moved the whole doc repository "As Is". It will be too time consumming to change all the build scripts only to adapt some paths. The doc should be easy to contribute from now on.
