### ISSUE TITLE
Enable Travis CI

### ISSUE THREAD

**Issue by tajmone** [fantaisie-software/purebasic#7]
Fred, could you enable Travis CI on this repository?

The current `.travis.yml` was already tested and is able to validate all commits and PRs against EditorConfig settings via EClint.

Once you enable Travis on the repository we can add a build-status badge in the README.

> __PS__: If you have an old Travis account from [travis-ci.org] you'll have to migrate all your repositories to [travis-ci.com] because recently GitHub changed their interfacing system to Travis. Migrating from the old system/site to the new one is a one-click operation, no pains at all. But the old system ceases to work completely last week.

[travis-ci.org]: https://travis-ci.org
[travis-ci.com]: https://travis-ci.com

**Comment by fantaisie-software** [comment]
Done, added the badge as well.
