### ISSUE TITLE
Tracking PB Documentation TODOs

### ISSUE THREAD

**Issue by tajmone** [fantaisie-software/purebasic#79]
This repository has seen many fixes, improvements and some new features to the PureBasic IDE and Debugger. I think we need to start tracking these changes for inclusion in the PB Help documentation.

Since the Help is not currently part of this project (see #61), the best choice at this moment might be creating dedicated Issues for tracking TODOs updates for the Help file, so that the Documentation Team can follow up on these changes without having to manually sift through every PR.

I've added a new  <kbd>[⚙ PB Help][PB Help label]</kbd> label that can be used to tag Issues relating to Documentation TODOs. So whenever a contributor edits or adds a IDE/Debugger feature that requires updating the PB Help dos, he/she might also create a dedicated Issue describing the required Documentation changes, by describing what has changed and/or proposing a text amendment.

Some of the new changes might affect the IDE menus and options and also require updating the IDE screenshots, in such cases it might be worth mentioning it.

Hopefully, in the future the Help sources will become part of this project, making it easier to update the Documentation in real time whenever any significant changes are made to the IDE or Debugger.

[PB Help label]: https://github.com/fantaisie-software/purebasic/labels/%3Agear%3A%20PB%20Help

**Comment by fantaisie-software** [comment]
The Help is now part of the repo, so I think we can close this.
