### ISSUE TITLE
More Options to Close Tabs/Files

### ISSUE THREAD

**Issue by tajmone** [fantaisie-software/purebasic#85]
When working with multiple files, the IDE currently offers only the option to close the current tab/file or all tabs/files.

It would be useful to have more options in the <kbd>File</kbd> menu and in the contextual menu shown when right-clicking on a file-tab:

- [ ] Close Other Tabs
- [ ] Close Tabs to the Right

This would spare end users having to close multiple files one by one (via <kbd>Ctrl</kbd>+<kbd>W</kbd>), allowing them to easily close every tab/file to the right of a given tab instead. Since tabs are drag-&-droppable, it would become very easy to quickly move to the left all the tabs that should be left open.

**Comment by fantaisie-software** [comment]
I would prefer to continue to use the forum 'feature requests' for this, so it will be centralised for everyone. 'Issues' should be only real issue related to the IDE or git related
