### ISSUE TITLE
Replacing HTTP with HTTPS Everywhere

### ISSUE THREAD

**Issue by tajmone** [fantaisie-software/purebasic#9]
I've noticed that the URL `http://www.purebasic.com` occurs in various places (11, to be precise), ranging from code sources (actual URLs used by applications, or just printed strings) as well as documentation.

I suggest substituting all its occurrences with `https://` instead of `http://`. Although the website automatically switches to secure HTTP even if  `http://` is used, I think it's a good idea to use the secure version instead, everywhere (since it supports the secure protocol, why use the unsecure one?). 

Also, I'm fairly sure that also replacing all occurrences in the PB IDE sources should be safe to do without breaking anything — i.e. regarding the code that handles updates checks. This is actually the part that deserves more to be switched to HTTPS. But this needs to be checked, for I've come across websites that supported HTTPS for navigation but not for downloading, so you never know with the WWW.

If you give me the green light on this I'll be happy to do the changes myself.

**Comment by fantaisie-software** [comment]
OK, makes sense

**Comment by tajmone** [comment]
😄 Look cool! (who said there's no beauty in tech-tools?)
